# Generated by Django 5.1.2 on 2024-10-22 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtendedSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        max_length=5, unique=True, verbose_name="Код валюты"
                    ),
                ),
                (
                    "currency_symbol",
                    models.CharField(max_length=5, verbose_name="Знак валюты"),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="extended",
                        to="sites.site",
                    ),
                ),
            ],
        ),
    ]
