# Generated by Django 5.1.2 on 2024-10-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extended_contrib_models", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extendedsite",
            options={
                "verbose_name": "Расширенные данные о сайте",
                "verbose_name_plural": "Расширенные данные о сайте",
            },
        ),
    ]
