# Generated by Django 5.1.2 on 2024-11-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extended_contrib_models", "0002_alter_extendedsite_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedsite",
            name="city",
            field=models.CharField(
                default="Berlin", max_length=40, verbose_name="Название города"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="city_en",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Название города"
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="city_ru",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Название города"
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="country",
            field=models.CharField(
                default="Germany", max_length=40, verbose_name="Название страны"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="country_en",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Название страны"
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="country_ru",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Название страны"
            ),
        ),
    ]
