# Generated by Django 5.1.2 on 2024-11-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "extended_contrib_models",
            "0003_extendedsite_city_extendedsite_city_en_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "absolute_path",
                    models.URLField(unique=True, verbose_name="Ссылка на соц. сеть"),
                ),
                (
                    "bootstrap_button_outline",
                    models.CharField(
                        choices=[
                            ("btn-outline-primary", "Primary - Blue"),
                            ("btn-outline-secondary", "Secondary - Gray"),
                            ("btn-outline-success", "Success - Green"),
                            ("btn-outline-danger", "Danger - Red"),
                            ("btn-outline-warning", "Warning - Yellow"),
                            ("btn-outline-info", "Info - Cyan"),
                            ("btn-outline-light", "Light - White"),
                            ("btn-outline-dark", "Dark - Black"),
                        ],
                        help_text="https://getbootstrap.com/docs/5.3/components/buttons/#outline-buttons",
                        max_length=40,
                        verbose_name="Название класса обводки кнопки из bootstrap (btn-outline-*)",
                    ),
                ),
                (
                    "bootstrap_icon",
                    models.CharField(
                        help_text="https://icons.getbootstrap.com/",
                        max_length=40,
                        verbose_name="Название класса иконки",
                    ),
                ),
            ],
        ),
    ]
