# Generated by Django 5.1.2 on 2024-11-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extended_contrib_models", "0004_social"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedsite",
            name="socials",
            field=models.ManyToManyField(
                related_name="site", to="extended_contrib_models.social"
            ),
        ),
    ]
