# Generated by Django 5.1.2 on 2024-11-03 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extended_contrib_models", "0005_extendedsite_socials"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extendedsite",
            name="socials",
        ),
        migrations.AddField(
            model_name="social",
            name="extended_site",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="socials",
                to="extended_contrib_models.extendedsite",
            ),
            preserve_default=False,
        ),
    ]
