# Generated by Django 5.1.2 on 2024-11-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "extended_contrib_models",
            "0006_remove_extendedsite_socials_social_extended_site",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="social",
            old_name="absolute_path",
            new_name="absolute_url",
        ),
    ]
