# Generated by Django 5.1.2 on 2024-11-03 17:17

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extended_contrib_models", "0007_rename_absolute_path_social_absolute_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="social",
            options={"verbose_name": "Соц. сеть", "verbose_name_plural": "Соц. сети"},
        ),
        migrations.RemoveField(
            model_name="social",
            name="bootstrap_button_outline",
        ),
        migrations.AddField(
            model_name="social",
            name="background_hex_code",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                help_text="Введите HEX-код цвета, например: #FFFFFF (белый) или #FFF (сокращённый формат).",
                image_field=None,
                max_length=25,
                samples=None,
                unique=True,
                verbose_name="HEX код цвета (#f4678a к примеру)",
            ),
        ),
    ]
