# Generated by Django 5.1.3 on 2024-11-21 23:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extended_contrib_models", "0010_alter_social_background_hex_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedsite",
            name="tax_percent",
            field=models.IntegerField(
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Скидка",
            ),
        ),
    ]
