# Generated by Django 5.1.3 on 2024-11-22 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extended_contrib_models", "0011_extendedsite_tax_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extendedsite",
            name="tax_percent",
            field=models.IntegerField(
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="НДС",
            ),
        ),
    ]
