# Generated by Django 5.1.3 on 2024-11-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extended_contrib_models", "0013_extendedsite_account_name_extendedsite_iban"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedsite",
            name="city_de",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Название города"
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="country_de",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Название страны"
            ),
        ),
    ]
