# Generated by Django 5.1.3 on 2024-11-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "extended_contrib_models",
            "0014_extendedsite_city_de_extendedsite_country_de",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="extendedsite",
            name="account_name",
            field=models.CharField(max_length=100, verbose_name="Название счёта"),
        ),
        migrations.AlterField(
            model_name="extendedsite",
            name="iban",
            field=models.CharField(max_length=100, verbose_name="IBAN для оплаты"),
        ),
    ]
