# Generated by Django 5.1.3 on 2024-11-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extended_contrib_models", "0015_alter_extendedsite_account_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedsite",
            name="country_iso_3166_1_alpha_2",
            field=models.CharField(
                default="DE",
                help_text="ISO 3166-1 alpha-2",
                max_length=2,
                verbose_name="Код страны ISO 3166-1 alpha-2",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="country_iso_3166_1_alpha_2_de",
            field=models.CharField(
                help_text="ISO 3166-1 alpha-2",
                max_length=2,
                null=True,
                verbose_name="Код страны ISO 3166-1 alpha-2",
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="country_iso_3166_1_alpha_2_en",
            field=models.CharField(
                help_text="ISO 3166-1 alpha-2",
                max_length=2,
                null=True,
                verbose_name="Код страны ISO 3166-1 alpha-2",
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="country_iso_3166_1_alpha_2_ru",
            field=models.CharField(
                help_text="ISO 3166-1 alpha-2",
                max_length=2,
                null=True,
                verbose_name="Код страны ISO 3166-1 alpha-2",
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="header_alert_message",
            field=models.CharField(
                default="Die Website befindet sich im Entwicklungsmodus. Bald sind wir für Sie da! Zurzeit ist es nicht möglich, eine Bestellung aufzugeben.",
                max_length=174,
                verbose_name="Текст для красного уведомления под хедером, белый текст на красном фоне во всю ширину строки.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="header_alert_message_de",
            field=models.CharField(
                max_length=174,
                null=True,
                verbose_name="Текст для красного уведомления под хедером, белый текст на красном фоне во всю ширину строки.",
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="header_alert_message_en",
            field=models.CharField(
                max_length=174,
                null=True,
                verbose_name="Текст для красного уведомления под хедером, белый текст на красном фоне во всю ширину строки.",
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="header_alert_message_ru",
            field=models.CharField(
                max_length=174,
                null=True,
                verbose_name="Текст для красного уведомления под хедером, белый текст на красном фоне во всю ширину строки.",
            ),
        ),
    ]
