# Generated by Django 5.1.3 on 2024-12-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "extended_contrib_models",
            "0017_remove_extendedsite_country_iso_3166_1_alpha_2_de_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedsite",
            name="city_ua",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Название города"
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="country_ua",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Название страны"
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="header_alert_message_ua",
            field=models.CharField(
                max_length=174,
                null=True,
                verbose_name="Текст для красного уведомления под хедером, белый текст на красном фоне во всю ширину строки.",
            ),
        ),
    ]
