# Generated by Django 5.1.4 on 2025-01-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "extended_contrib_models",
            "0019_rename_city_ua_extendedsite_city_uk_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedsite",
            name="email",
            field=models.CharField(
                default="service@blumenhorizon.de",
                max_length=50,
                verbose_name="Email компании",
            ),
        ),
    ]
