# Generated by Django 5.1.4 on 2025-01-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extended_contrib_models", "0020_extendedsite_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extendedsite",
            name="header_alert_message",
            field=models.CharField(
                max_length=174,
                null=True,
                verbose_name="Текст для красного уведомления под хедером, белый текст на красном фоне во всю ширину строки.",
            ),
        ),
    ]
