# Generated by Django 5.1.4 on 2025-01-15 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extended_contrib_models", "0021_alter_extendedsite_header_alert_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extendedsite",
            name="account_name",
        ),
        migrations.RemoveField(
            model_name="extendedsite",
            name="iban",
        ),
    ]
