# Generated by Django 5.1.4 on 2025-01-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extended_contrib_models", "0022_remove_extendedsite_account_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extendedsite",
            name="header_alert_message",
            field=models.CharField(
                blank=True,
                max_length=174,
                null=True,
                verbose_name="Текст для красного уведомления под хедером, белый текст на красном фоне во всю ширину строки.",
            ),
        ),
        migrations.AlterField(
            model_name="extendedsite",
            name="header_alert_message_de",
            field=models.CharField(
                blank=True,
                max_length=174,
                null=True,
                verbose_name="Текст для красного уведомления под хедером, белый текст на красном фоне во всю ширину строки.",
            ),
        ),
        migrations.AlterField(
            model_name="extendedsite",
            name="header_alert_message_en",
            field=models.CharField(
                blank=True,
                max_length=174,
                null=True,
                verbose_name="Текст для красного уведомления под хедером, белый текст на красном фоне во всю ширину строки.",
            ),
        ),
        migrations.AlterField(
            model_name="extendedsite",
            name="header_alert_message_ru",
            field=models.CharField(
                blank=True,
                max_length=174,
                null=True,
                verbose_name="Текст для красного уведомления под хедером, белый текст на красном фоне во всю ширину строки.",
            ),
        ),
        migrations.AlterField(
            model_name="extendedsite",
            name="header_alert_message_uk",
            field=models.CharField(
                blank=True,
                max_length=174,
                null=True,
                verbose_name="Текст для красного уведомления под хедером, белый текст на красном фоне во всю ширину строки.",
            ),
        ),
    ]
