# Generated by Django 5.1.4 on 2025-02-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "extended_contrib_models",
            "0023_alter_extendedsite_header_alert_message_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extendedsite",
            name="tax_percent",
        ),
    ]
