# Generated by Django 5.1.4 on 2025-04-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extended_contrib_models", "0024_remove_extendedsite_tax_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedsite",
            name="city_es",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Название города"
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="country_es",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Название страны"
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="header_alert_message_es",
            field=models.CharField(
                blank=True,
                max_length=174,
                null=True,
                verbose_name="Текст для красного уведомления под хедером, белый текст на красном фоне во всю ширину строки.",
            ),
        ),
    ]
