# Generated by Django 5.1.4 on 2025-02-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extended_contrib_models', '0024_remove_extendedsite_city_remove_extendedsite_city_de_and_more'),
        ('extended_contrib_models', '0024_remove_extendedsite_tax_percent'),
    ]

    operations = [
    ]
