# Generated by Django 5.1 on 2025-04-19 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extended_contrib_models", "0024_remove_extendedsite_tax_percent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Filial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="ISO",
                        max_length=60,
                        verbose_name="Название “Город/Страна”",
                    ),
                ),
                ("url", models.URLField(verbose_name="Ссылка на филиал")),
                (
                    "extended_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="filials",
                        to="extended_contrib_models.extendedsite",
                    ),
                ),
            ],
        ),
    ]
