# Generated by Django 5.1.4 on 2025-02-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "extended_contrib_models",
            "0025_extendedsite_city_gr_extendedsite_country_gr_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="extendedsite",
            old_name="city_gr",
            new_name="city_el",
        ),
        migrations.RenameField(
            model_name="extendedsite",
            old_name="country_gr",
            new_name="country_el",
        ),
        migrations.RenameField(
            model_name="extendedsite",
            old_name="header_alert_message_gr",
            new_name="header_alert_message_el",
        ),
    ]
