# Generated by Django 5.1 on 2025-04-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extended_contrib_models", "0025_filial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filial",
            name="title_de",
            field=models.CharField(
                help_text="ISO",
                max_length=60,
                null=True,
                verbose_name="Название “Город/Страна”",
            ),
        ),
        migrations.AddField(
            model_name="filial",
            name="title_en",
            field=models.CharField(
                help_text="ISO",
                max_length=60,
                null=True,
                verbose_name="Название “Город/Страна”",
            ),
        ),
        migrations.AddField(
            model_name="filial",
            name="title_ru",
            field=models.CharField(
                help_text="ISO",
                max_length=60,
                null=True,
                verbose_name="Название “Город/Страна”",
            ),
        ),
        migrations.AddField(
            model_name="filial",
            name="title_uk",
            field=models.CharField(
                help_text="ISO",
                max_length=60,
                null=True,
                verbose_name="Название “Город/Страна”",
            ),
        ),
        migrations.AddField(
            model_name="filial",
            name="url_de",
            field=models.URLField(null=True, verbose_name="Ссылка на филиал"),
        ),
        migrations.AddField(
            model_name="filial",
            name="url_en",
            field=models.URLField(null=True, verbose_name="Ссылка на филиал"),
        ),
        migrations.AddField(
            model_name="filial",
            name="url_ru",
            field=models.URLField(null=True, verbose_name="Ссылка на филиал"),
        ),
        migrations.AddField(
            model_name="filial",
            name="url_uk",
            field=models.URLField(null=True, verbose_name="Ссылка на филиал"),
        ),
    ]
