# Generated by Django 5.1 on 2025-04-20 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "extended_contrib_models",
            "0026_filial_title_de_filial_title_en_filial_title_ru_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filial",
            options={
                "verbose_name": "Страница «Филиалы»",
                "verbose_name_plural": "Страница «Филиалы»",
            },
        ),
        migrations.AlterField(
            model_name="filial",
            name="extended_site",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="filials",
                to="extended_contrib_models.extendedsite",
            ),
        ),
    ]
