# Generated by Django 5.1.4 on 2025-05-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extended_contrib_models', '0027_alter_filial_options_alter_filial_extended_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filial',
            options={'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.AddField(
            model_name='extendedsite',
            name='parent_organization_url',
            field=models.URLField(default='https://blumenhorizon.de/', verbose_name='Ссылка на родительскую организацию'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendedsite',
            name='parent_organization_url_de',
            field=models.URLField(null=True, verbose_name='Ссылка на родительскую организацию'),
        ),
        migrations.AddField(
            model_name='extendedsite',
            name='parent_organization_url_en',
            field=models.URLField(null=True, verbose_name='Ссылка на родительскую организацию'),
        ),
        migrations.AddField(
            model_name='extendedsite',
            name='parent_organization_url_ru',
            field=models.URLField(null=True, verbose_name='Ссылка на родительскую организацию'),
        ),
        migrations.AddField(
            model_name='extendedsite',
            name='parent_organization_url_uk',
            field=models.URLField(null=True, verbose_name='Ссылка на родительскую организацию'),
        ),
    ]
