# Generated by Django 5.1.4 on 2025-04-20 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extended_contrib_models', '0027_alter_filial_options_alter_filial_extended_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filial',
            options={'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
    ]
