# Generated by Django 5.1.4 on 2025-04-20 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extended_contrib_models', '0028_merge_20250421_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filial',
            options={'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
    ]
