# Generated by Django 5.1.4 on 2025-04-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extended_contrib_models", "0028_merge_20250421_0126"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filial",
            options={"verbose_name": "Филиал", "verbose_name_plural": "Филиалы"},
        ),
        migrations.AddField(
            model_name="filial",
            name="title_es",
            field=models.CharField(
                help_text="ISO",
                max_length=60,
                null=True,
                verbose_name="Название “Город/Страна”",
            ),
        ),
        migrations.AddField(
            model_name="filial",
            name="url_es",
            field=models.URLField(null=True, verbose_name="Ссылка на филиал"),
        ),
    ]
