# Generated by Django 5.1.4 on 2025-05-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "extended_contrib_models",
            "0029_alter_filial_options_filial_title_el_filial_url_el",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedsite",
            name="Ссылка на родительскую организацию",
            field=models.URLField(default="https://blumenhorizon.de/"),
            preserve_default=False,
        ),
    ]
