# Generated by Django 5.1.4 on 2025-05-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "extended_contrib_models",
            "0029_alter_filial_options_filial_title_es_filial_url_es",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedsite",
            name="parent_organization_url",
            field=models.URLField(
                default="https://blumenhorizon.de/",
                verbose_name="Ссылка на родительскую организацию",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="parent_organization_url_de",
            field=models.URLField(
                null=True, verbose_name="Ссылка на родительскую организацию"
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="parent_organization_url_en",
            field=models.URLField(
                null=True, verbose_name="Ссылка на родительскую организацию"
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="parent_organization_url_es",
            field=models.URLField(
                null=True, verbose_name="Ссылка на родительскую организацию"
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="parent_organization_url_ru",
            field=models.URLField(
                null=True, verbose_name="Ссылка на родительскую организацию"
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="parent_organization_url_uk",
            field=models.URLField(
                null=True, verbose_name="Ссылка на родительскую организацию"
            ),
        ),
    ]
