# Generated by Django 5.1.4 on 2025-05-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extended_contrib_models", "0030_extendedsite_parent_organization_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedsite",
            name="parent_organization_url_de",
            field=models.URLField(
                null=True, verbose_name="Ссылка на родительскую организацию"
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="parent_organization_url_el",
            field=models.URLField(
                null=True, verbose_name="Ссылка на родительскую организацию"
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="parent_organization_url_en",
            field=models.URLField(
                null=True, verbose_name="Ссылка на родительскую организацию"
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="parent_organization_url_ru",
            field=models.URLField(
                null=True, verbose_name="Ссылка на родительскую организацию"
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="parent_organization_url_uk",
            field=models.URLField(
                null=True, verbose_name="Ссылка на родительскую организацию"
            ),
        ),
    ]
