# Generated by Django 5.1.2 on 2024-10-19 10:53

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_user_phone_number_user_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phonenumber",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=15,
                null=True,
                region=None,
                unique=True,
                verbose_name="Номер телефона",
            ),
        ),
    ]
