# Generated by Django 5.1.2 on 2024-11-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_user_is_staff_alter_user_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Определяет может ли пользователь попасть в админ-панель.",
                verbose_name="Администратор?",
            ),
        ),
    ]
