# Generated by Django 5.1.2 on 2024-10-26 00:20

import colorfield.fields
import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bouquet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=40, null=True, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=40, null=True, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(unique=True, verbose_name="Название в ссылке"),
                ),
                (
                    "slug_ru",
                    models.SlugField(
                        null=True, unique=True, verbose_name="Название в ссылке"
                    ),
                ),
                (
                    "slug_en",
                    models.SlugField(
                        null=True, unique=True, verbose_name="Название в ссылке"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный?"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Цена продукта до 10ти значений, два из которых плавающая запятая. Т.е. до 99999999.99",
                        max_digits=10,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Скидка",
                    ),
                ),
                ("description", tinymce.models.HTMLField(verbose_name="Описание")),
                (
                    "description_ru",
                    tinymce.models.HTMLField(null=True, verbose_name="Описание"),
                ),
                (
                    "description_en",
                    tinymce.models.HTMLField(null=True, verbose_name="Описание"),
                ),
                ("specs", tinymce.models.HTMLField(verbose_name="Характеристики")),
                (
                    "specs_ru",
                    tinymce.models.HTMLField(null=True, verbose_name="Характеристики"),
                ),
                (
                    "specs_en",
                    tinymce.models.HTMLField(null=True, verbose_name="Характеристики"),
                ),
                ("size", models.IntegerField(verbose_name="Диаметр букета")),
                (
                    "amount_of_flowers",
                    models.IntegerField(verbose_name="Количество цветов в букете"),
                ),
            ],
            options={
                "verbose_name": "Букет",
                "verbose_name_plural": "Букеты",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=40, null=True, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=40, null=True, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(unique=True, verbose_name="Название в ссылке"),
                ),
                (
                    "slug_ru",
                    models.SlugField(
                        null=True, unique=True, verbose_name="Название в ссылке"
                    ),
                ),
                (
                    "slug_en",
                    models.SlugField(
                        null=True, unique=True, verbose_name="Название в ссылке"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный?"),
                ),
                (
                    "image",
                    models.ImageField(
                        default="defaults/no-image.webp",
                        upload_to="categories/%Y-%m-%d",
                        verbose_name="Картинка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=15, null=True, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=15, null=True, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "hex_code",
                    colorfield.fields.ColorField(
                        default="#FFFFFF",
                        help_text="Введите HEX-код цвета, например: #FFFFFF (белый) или #FFF (сокращённый формат).",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        unique=True,
                        verbose_name="HEX код цвета (#f4678a к примеру)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цвет",
                "verbose_name_plural": "Цвета",
            },
        ),
        migrations.CreateModel(
            name="Flower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=30, null=True, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=30, null=True, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Цветок",
                "verbose_name_plural": "Цветы",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=40, null=True, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=40, null=True, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(unique=True, verbose_name="Название в ссылке"),
                ),
                (
                    "slug_ru",
                    models.SlugField(
                        null=True, unique=True, verbose_name="Название в ссылке"
                    ),
                ),
                (
                    "slug_en",
                    models.SlugField(
                        null=True, unique=True, verbose_name="Название в ссылке"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный?"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Цена продукта до 10ти значений, два из которых плавающая запятая. Т.е. до 99999999.99",
                        max_digits=10,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Скидка",
                    ),
                ),
                ("description", tinymce.models.HTMLField(verbose_name="Описание")),
                (
                    "description_ru",
                    tinymce.models.HTMLField(null=True, verbose_name="Описание"),
                ),
                (
                    "description_en",
                    tinymce.models.HTMLField(null=True, verbose_name="Описание"),
                ),
                ("specs", tinymce.models.HTMLField(verbose_name="Характеристики")),
                (
                    "specs_ru",
                    tinymce.models.HTMLField(null=True, verbose_name="Характеристики"),
                ),
                (
                    "specs_en",
                    tinymce.models.HTMLField(null=True, verbose_name="Характеристики"),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="BouquetImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/%Y-%m-%d/", verbose_name="Изображение"
                    ),
                ),
                (
                    "bouquet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalogue.bouquet",
                        verbose_name="Букет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение букета",
                "verbose_name_plural": "Изображения букетов",
            },
        ),
        migrations.AddField(
            model_name="bouquet",
            name="colors",
            field=models.ManyToManyField(
                help_text="Выберите какого цвета букет.",
                related_name="bouquets",
                to="catalogue.color",
                verbose_name="Цвета",
            ),
        ),
        migrations.AddField(
            model_name="bouquet",
            name="flowers",
            field=models.ManyToManyField(
                help_text="Выберите какие цветы в букете.",
                related_name="bouquets",
                to="catalogue.flower",
                verbose_name="Цветы",
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products_media/%Y-%m-%d/", verbose_name="Изображение"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalogue.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение продукта",
                "verbose_name_plural": "Изображения продуктов",
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=40, null=True, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=40, null=True, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(unique=True, verbose_name="Название в ссылке"),
                ),
                (
                    "slug_ru",
                    models.SlugField(
                        null=True, unique=True, verbose_name="Название в ссылке"
                    ),
                ),
                (
                    "slug_en",
                    models.SlugField(
                        null=True, unique=True, verbose_name="Название в ссылке"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный?"),
                ),
                (
                    "image",
                    models.ImageField(
                        default="defaults/no-image.webp",
                        upload_to="subcategories/%Y-%m-%d",
                        verbose_name="Картинка",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcategories",
                        to="catalogue.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подкатегория",
                "verbose_name_plural": "Подкатегории",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogue.subcategory",
                verbose_name="Подкатегория",
            ),
        ),
        migrations.AddField(
            model_name="bouquet",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogue.subcategory",
                verbose_name="Подкатегория",
            ),
        ),
    ]
