# Generated by Django 5.1.2 on 2024-10-29 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0002_alter_bouquet_subcategory_alter_product_subcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=40, null=True, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=40, null=True, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(unique=True, verbose_name="Название в ссылке"),
                ),
                (
                    "slug_ru",
                    models.SlugField(
                        null=True, unique=True, verbose_name="Название в ссылке"
                    ),
                ),
                (
                    "slug_en",
                    models.SlugField(
                        null=True, unique=True, verbose_name="Название в ссылке"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный?"),
                ),
                (
                    "image",
                    models.ImageField(
                        default="defaults/no-image.webp",
                        upload_to="categories/%Y-%m-%d",
                        verbose_name="Картинка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория продукта",
                "verbose_name_plural": "Категории продуктов",
            },
        ),
        migrations.RenameModel(
            old_name="Category",
            new_name="BouquetCategory",
        ),
        migrations.RenameModel(
            old_name="Subcategory",
            new_name="BouquetSubcategory",
        ),
        migrations.AlterModelOptions(
            name="bouquetcategory",
            options={
                "verbose_name": "Категория букета",
                "verbose_name_plural": "Категории букетов",
            },
        ),
        migrations.AlterModelOptions(
            name="bouquetsubcategory",
            options={
                "verbose_name": "Подкатегория букета",
                "verbose_name_plural": "Подкатегории букетов",
            },
        ),
        migrations.CreateModel(
            name="ProductSubcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=40, null=True, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=40, null=True, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(unique=True, verbose_name="Название в ссылке"),
                ),
                (
                    "slug_ru",
                    models.SlugField(
                        null=True, unique=True, verbose_name="Название в ссылке"
                    ),
                ),
                (
                    "slug_en",
                    models.SlugField(
                        null=True, unique=True, verbose_name="Название в ссылке"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный?"),
                ),
                (
                    "image",
                    models.ImageField(
                        default="defaults/no-image.webp",
                        upload_to="subcategories/%Y-%m-%d",
                        verbose_name="Картинка",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcategories",
                        to="catalogue.productcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подкатегория продукта",
                "verbose_name_plural": "Подкатегории продуктов",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalogue.productsubcategory",
                verbose_name="Подкатегория",
            ),
        ),
    ]
