# Generated by Django 5.1.2 on 2024-11-08 00:52

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0008_alter_bouquet_sku_alter_product_sku"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndividualQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phonenumber",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=15,
                        null=True,
                        region=None,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "bouquet",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="individual_question",
                        to="catalogue.bouquet",
                        verbose_name="Связанный букет",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="individual_question",
                        to="catalogue.product",
                        verbose_name="Связанный продукт",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individual_questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Связанный аккаунт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Индивидуальный вопрос о продукте",
                "verbose_name_plural": "Индивидуальные вопросы о продуктах",
            },
        ),
    ]
