# Generated by Django 5.1.2 on 2024-11-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0009_individualquestion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="individualquestion",
            name="phonenumber",
        ),
        migrations.AddField(
            model_name="individualquestion",
            name="contact_method",
            field=models.TextField(
                default="a", max_length=100, verbose_name="Способ связи с клиентом"
            ),
            preserve_default=False,
        ),
    ]
