# Generated by Django 5.1.2 on 2024-11-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0010_remove_individualquestion_phonenumber_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="individualquestion",
            name="recall_me",
            field=models.BooleanField(
                default=False, verbose_name="Разрешил ли клиент звонить ему"
            ),
        ),
    ]
