# Generated by Django 5.1.2 on 2024-11-08 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0011_individualquestion_recall_me"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individualquestion",
            name="bouquet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="individual_question",
                to="catalogue.bouquet",
                verbose_name="Связанный букет",
            ),
        ),
        migrations.AlterField(
            model_name="individualquestion",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="individual_question",
                to="catalogue.product",
                verbose_name="Связанный продукт",
            ),
        ),
    ]
