# Generated by Django 5.1.2 on 2024-11-11 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0014_bouquetssizes_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bouquet",
            name="sizes",
        ),
        migrations.AddField(
            model_name="bouquetssizes",
            name="bouquet",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sizes",
                to="catalogue.bouquet",
                verbose_name="Букет",
            ),
            preserve_default=False,
        ),
    ]
