# Generated by Django 5.1.2 on 2024-11-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0015_remove_bouquet_sizes_bouquetssizes_bouquet"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BouquetsSizes",
            new_name="BouquetSize",
        ),
    ]
