# Generated by Django 5.1.2 on 2024-11-11 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0016_rename_bouquetssizes_bouquetsize"),
    ]

    operations = [
        migrations.CreateModel(
            name="BouquetSizeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/sizes/bouquets/%Y-%m-%d/",
                        verbose_name="Изображение размера букета",
                    ),
                ),
                (
                    "bouquet_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalogue.bouquetsize",
                        verbose_name="Размер букета",
                    ),
                ),
            ],
        ),
    ]
