# Generated by Django 5.1.2 on 2024-11-11 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0017_bouquetsizeimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bouquetsizeimage",
            options={
                "verbose_name": "Изображение размера букета",
                "verbose_name_plural": "Изображения размеров букетов",
            },
        ),
    ]
