# Generated by Django 5.1.2 on 2024-11-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0018_alter_bouquetsizeimage_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bouquetimage",
            name="image",
            field=models.ImageField(
                upload_to="bouquets/%Y-%m-%d/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsizeimage",
            name="image",
            field=models.ImageField(
                upload_to="bouquets/sizes/bouquets/%Y-%m-%d/",
                verbose_name="Изображение размера букета",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="products/%Y-%m-%d/", verbose_name="Изображение"
            ),
        ),
    ]
