# Generated by Django 5.1.2 on 2024-11-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0019_alter_bouquetimage_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bouquetsizeimage",
            name="image",
            field=models.ImageField(
                upload_to="bouquets/sizes/%Y-%m-%d/",
                verbose_name="Изображение размера букета",
            ),
        ),
    ]
