# Generated by Django 5.1.2 on 2024-11-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0020_alter_bouquetsizeimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bouquetcategory",
            name="image",
            field=models.ImageField(
                upload_to="categories/%Y-%m-%d", verbose_name="Картинка"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="image",
            field=models.ImageField(
                upload_to="subcategories/%Y-%m-%d", verbose_name="Картинка"
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="image",
            field=models.ImageField(
                upload_to="categories/%Y-%m-%d", verbose_name="Картинка"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/%Y-%m-%d/"),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="image",
            field=models.ImageField(
                upload_to="subcategories/%Y-%m-%d", verbose_name="Картинка"
            ),
        ),
    ]
