# Generated by Django 5.1.2 on 2024-11-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0022_bouquetcategory_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bouquetcategory",
            name="amount_of_orders",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="Количество заказов"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bouquetcategory",
            name="amount_of_savings",
            field=models.IntegerField(
                default=0,
                editable=False,
                verbose_name="Количество добавлений в корзину",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bouquetsubcategory",
            name="amount_of_orders",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="Количество заказов"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bouquetsubcategory",
            name="amount_of_savings",
            field=models.IntegerField(
                default=0,
                editable=False,
                verbose_name="Количество добавлений в корзину",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productcategory",
            name="amount_of_orders",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="Количество заказов"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productcategory",
            name="amount_of_savings",
            field=models.IntegerField(
                default=0,
                editable=False,
                verbose_name="Количество добавлений в корзину",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="amount_of_orders",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="Количество заказов"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="amount_of_savings",
            field=models.IntegerField(
                default=0,
                editable=False,
                verbose_name="Количество добавлений в корзину",
            ),
            preserve_default=False,
        ),
    ]
