# Generated by Django 5.1.2 on 2024-11-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0023_bouquetcategory_amount_of_orders_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bouquetcategory",
            name="image_alt",
            field=models.CharField(
                default="", max_length=100, verbose_name="Описание картинки"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bouquetcategory",
            name="image_alt_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="bouquetcategory",
            name="image_alt_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="bouquetimage",
            name="image_alt",
            field=models.CharField(
                default="", max_length=100, verbose_name="Описание картинки"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bouquetimage",
            name="image_alt_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="bouquetimage",
            name="image_alt_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="bouquetsizeimage",
            name="image_alt",
            field=models.CharField(
                default="", max_length=100, verbose_name="Описание картинки"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bouquetsizeimage",
            name="image_alt_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="bouquetsizeimage",
            name="image_alt_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="bouquetsubcategory",
            name="image_alt",
            field=models.CharField(
                default="", max_length=100, verbose_name="Описание картинки"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bouquetsubcategory",
            name="image_alt_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="bouquetsubcategory",
            name="image_alt_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="image_alt",
            field=models.CharField(
                default="", max_length=100, verbose_name="Описание картинки"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productcategory",
            name="image_alt_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="image_alt_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="image_alt",
            field=models.CharField(
                default="", max_length=100, verbose_name="Описание картинки"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productimage",
            name="image_alt_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="image_alt_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="image_alt",
            field=models.CharField(
                default="", max_length=100, verbose_name="Описание картинки"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="image_alt_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="image_alt_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
    ]
