# Generated by Django 5.1.2 on 2024-11-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0024_bouquetcategory_image_alt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bouquetcategory",
            name="image",
            field=models.ImageField(
                default="defaults/no-image.webp",
                upload_to="categories/%Y-%m-%d",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="image",
            field=models.ImageField(
                default="defaults/no-image.webp",
                upload_to="categories/%Y-%m-%d",
                verbose_name="Картинка",
            ),
        ),
    ]
