# Generated by Django 5.1.2 on 2024-11-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0025_alter_bouquetcategory_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bouquet",
            name="amount_of_orders",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="Количество заказов"
            ),
        ),
        migrations.AlterField(
            model_name="bouquet",
            name="amount_of_savings",
            field=models.IntegerField(
                default=0,
                editable=False,
                verbose_name="Количество добавлений в корзину",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="amount_of_orders",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="Количество заказов"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="amount_of_savings",
            field=models.IntegerField(
                default=0,
                editable=False,
                verbose_name="Количество добавлений в корзину",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="amount_of_orders",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="Количество заказов"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="amount_of_savings",
            field=models.IntegerField(
                default=0,
                editable=False,
                verbose_name="Количество добавлений в корзину",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="image",
            field=models.ImageField(
                default="defaults/no-image.webp",
                upload_to="subcategories/%Y-%m-%d",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="amount_of_orders",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="Количество заказов"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="amount_of_savings",
            field=models.IntegerField(
                default=0,
                editable=False,
                verbose_name="Количество добавлений в корзину",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="amount_of_orders",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="Количество заказов"
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="amount_of_savings",
            field=models.IntegerField(
                default=0,
                editable=False,
                verbose_name="Количество добавлений в корзину",
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="amount_of_orders",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="Количество заказов"
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="amount_of_savings",
            field=models.IntegerField(
                default=0,
                editable=False,
                verbose_name="Количество добавлений в корзину",
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="image",
            field=models.ImageField(
                default="defaults/no-image.webp",
                upload_to="subcategories/%Y-%m-%d",
                verbose_name="Картинка",
            ),
        ),
    ]
