# Generated by Django 5.1.2 on 2024-11-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0026_alter_bouquet_amount_of_orders_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bouquet",
            name="colors",
            field=models.ManyToManyField(
                help_text="Выберите какого цвета букет.",
                related_name="bouquet",
                to="catalogue.color",
                verbose_name="Цветовые гаммы букетов",
            ),
        ),
        migrations.AlterField(
            model_name="bouquet",
            name="flowers",
            field=models.ManyToManyField(
                help_text="Выберите какие цветы в букете.",
                related_name="bouquets",
                to="catalogue.flower",
                verbose_name="Состав букетов",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetimage",
            name="image",
            field=models.ImageField(
                default="defaults/no-image.webp",
                upload_to="bouquets/%Y-%m-%d/",
                verbose_name="Изображение букета",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsizeimage",
            name="image",
            field=models.ImageField(
                default="defaults/no-image.webp",
                upload_to="bouquets/sizes/%Y-%m-%d/",
                verbose_name="Изображение размера букета",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                default="defaults/no-image.webp",
                upload_to="products/%Y-%m-%d/",
                verbose_name="Изображение продукта",
            ),
        ),
    ]
