# Generated by Django 5.1.2 on 2024-11-14 14:05

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0030_alter_individualquestion_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogPageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_tags", tinymce.models.HTMLField(verbose_name="Мета-теги")),
            ],
        ),
        migrations.CreateModel(
            name="CategoryPageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_tags", tinymce.models.HTMLField(verbose_name="Мета-теги")),
            ],
        ),
        migrations.AddField(
            model_name="bouquet",
            name="meta_tags",
            field=tinymce.models.HTMLField(default="", verbose_name="Мета-теги"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bouquetcategory",
            name="meta_tags",
            field=tinymce.models.HTMLField(default="", verbose_name="Мета-теги"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bouquetsubcategory",
            name="meta_tags",
            field=tinymce.models.HTMLField(default="", verbose_name="Мета-теги"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="meta_tags",
            field=tinymce.models.HTMLField(default="", verbose_name="Мета-теги"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productcategory",
            name="meta_tags",
            field=tinymce.models.HTMLField(default="", verbose_name="Мета-теги"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="meta_tags",
            field=tinymce.models.HTMLField(default="", verbose_name="Мета-теги"),
            preserve_default=False,
        ),
    ]
