# Generated by Django 5.1.2 on 2024-11-14 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogue",
            "0031_catalogpagemodel_categorypagemodel_bouquet_meta_tags_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catalogpagemodel",
            options={
                "verbose_name": "Мета-тег каталога категорий и подкатегорий",
                "verbose_name_plural": "Мета-теги каталога категорий и подкатегорий",
            },
        ),
        migrations.AlterModelOptions(
            name="categorypagemodel",
            options={
                "verbose_name": "Мета-тег каталога подкатегорий категории",
                "verbose_name_plural": "Мета-теги каталога подкатегорий категории",
            },
        ),
    ]
