# Generated by Django 5.1.2 on 2024-11-14 14:42

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0032_alter_catalogpagemodel_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BouquetsListPageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_tags", tinymce.models.HTMLField(verbose_name="Мета-теги")),
            ],
            options={
                "verbose_name": "Мета-тег списка всех букетов",
                "verbose_name_plural": "Мета-теги списка всех букетов",
            },
        ),
        migrations.CreateModel(
            name="ProductsListPageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_tags", tinymce.models.HTMLField(verbose_name="Мета-теги")),
            ],
            options={
                "verbose_name": "Мета-тег списка всех продуктов",
                "verbose_name_plural": "Мета-теги списка всех продуктов",
            },
        ),
    ]
