# Generated by Django 5.1.2 on 2024-11-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0036_bouquet_meta_tags_en_bouquet_meta_tags_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bouquet",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=1000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="bouquetcategory",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=1000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="bouquetslistpagemodel",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=1000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="bouquetsubcategory",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=1000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="catalogpagemodel",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=1000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="categorypagemodel",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=1000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=1000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=1000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="productslistpagemodel",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=1000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=1000,
                verbose_name="JSON-LD",
            ),
        ),
    ]
