# Generated by Django 5.1.2 on 2024-11-18 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0037_bouquet_json_ld_bouquetcategory_json_ld_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bouquet",
            name="discount_expiration_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Время истечения скидки"
            ),
        ),
        migrations.AddField(
            model_name="bouquetsize",
            name="discount_expiration_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Время истечения скидки"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_expiration_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Время истечения скидки"
            ),
        ),
    ]
