# Generated by Django 5.1.3 on 2024-11-20 00:36

from django.db import migrations, models

import catalogue.models


def populate_code_values(apps, schema_editor):
    BouquetCategory = apps.get_model("catalogue", "BouquetCategory")
    BouquetSubCategory = apps.get_model("catalogue", "BouquetSubcategory")
    ProductCategory = apps.get_model("catalogue", "ProductCategory")
    ProductSubCategory = apps.get_model("catalogue", "ProductSubcategory")

    for model in [
        BouquetCategory,
        BouquetSubCategory,
        ProductCategory,
        ProductSubCategory,
    ]:
        for obj in model.objects.all():
            if not obj.code_value:
                obj.code_value = catalogue.models.generate_sku()
                obj.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogue",
            "0039_alter_bouquet_meta_tags_alter_bouquet_meta_tags_en_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bouquetcategory",
            name="code_value",
            field=models.CharField(default="", max_length=50, unique=False),
        ),
        migrations.AddField(
            model_name="bouquetsubcategory",
            name="code_value",
            field=models.CharField(default="", max_length=50, unique=False),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="code_value",
            field=models.CharField(default="", max_length=50, unique=False),
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="code_value",
            field=models.CharField(default="", max_length=50, unique=False),
        ),
        migrations.RunPython(populate_code_values),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="code_value",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="code_value",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="code_value",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="code_value",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
