# Generated by Django 5.1.3 on 2024-11-20 12:51

from django.db import migrations, models

import catalogue.models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0040_bouquetcategory_code_value_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CategoryPageModel",
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="code_value",
            field=models.CharField(
                default=catalogue.models.generate_sku, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="code_value",
            field=models.CharField(
                default=catalogue.models.generate_sku, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="code_value",
            field=models.CharField(
                default=catalogue.models.generate_sku, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="code_value",
            field=models.CharField(
                default=catalogue.models.generate_sku, max_length=50, unique=True
            ),
        ),
    ]
