# Generated by Django 5.1.3 on 2024-11-22 03:51

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0041_delete_categorypagemodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bouquet",
            name="description_de",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="bouquet",
            name="meta_tags_de",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AddField(
            model_name="bouquet",
            name="name_de",
            field=models.CharField(
                max_length=40, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="bouquet",
            name="slug_de",
            field=models.SlugField(
                null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AddField(
            model_name="bouquet",
            name="specs_de",
            field=tinymce.models.HTMLField(null=True, verbose_name="Характеристики"),
        ),
        migrations.AddField(
            model_name="bouquetcategory",
            name="image_alt_de",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="bouquetcategory",
            name="meta_tags_de",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AddField(
            model_name="bouquetcategory",
            name="name_de",
            field=models.CharField(
                max_length=40, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="bouquetcategory",
            name="slug_de",
            field=models.SlugField(
                null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AddField(
            model_name="bouquetimage",
            name="image_alt_de",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="bouquetsizeimage",
            name="image_alt_de",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="bouquetslistpagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AddField(
            model_name="bouquetsubcategory",
            name="image_alt_de",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="bouquetsubcategory",
            name="meta_tags_de",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AddField(
            model_name="bouquetsubcategory",
            name="name_de",
            field=models.CharField(
                max_length=40, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="bouquetsubcategory",
            name="slug_de",
            field=models.SlugField(
                null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AddField(
            model_name="catalogpagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AddField(
            model_name="color",
            name="name_de",
            field=models.CharField(
                max_length=15, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="flower",
            name="name_de",
            field=models.CharField(
                max_length=30, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_de",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_tags_de",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="name_de",
            field=models.CharField(
                max_length=40, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="slug_de",
            field=models.SlugField(
                null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="specs_de",
            field=tinymce.models.HTMLField(null=True, verbose_name="Характеристики"),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="image_alt_de",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="meta_tags_de",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="name_de",
            field=models.CharField(
                max_length=40, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="slug_de",
            field=models.SlugField(
                null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="image_alt_de",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="productslistpagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="image_alt_de",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="meta_tags_de",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="name_de",
            field=models.CharField(
                max_length=40, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="slug_de",
            field=models.SlugField(
                null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
    ]
