# Generated by Django 5.1.3 on 2024-11-22 20:09

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0042_bouquet_description_de_bouquet_meta_tags_de_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bouquet",
            name="sku",
            field=models.CharField(
                default=catalogue.models.generate_sku,
                max_length=25,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                default=catalogue.models.generate_sku,
                max_length=25,
                null=True,
                unique=True,
            ),
        ),
    ]
