# Generated by Django 5.1.3 on 2024-11-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0043_alter_bouquet_sku_alter_product_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bouquet",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="bouquet",
            name="meta_tags",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquet",
            name="meta_tags_de",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquet",
            name="meta_tags_en",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquet",
            name="meta_tags_ru",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquet",
            name="name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="bouquet",
            name="name_de",
            field=models.CharField(
                max_length=200, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="bouquet",
            name="name_en",
            field=models.CharField(
                max_length=200, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="bouquet",
            name="name_ru",
            field=models.CharField(
                max_length=200, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="meta_tags",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="meta_tags_de",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="meta_tags_en",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="meta_tags_ru",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="name_de",
            field=models.CharField(
                max_length=200, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="name_en",
            field=models.CharField(
                max_length=200, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="name_ru",
            field=models.CharField(
                max_length=200, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="meta_tags",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="meta_tags_de",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="meta_tags_en",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="meta_tags_ru",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="name_de",
            field=models.CharField(
                max_length=200, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="name_en",
            field=models.CharField(
                max_length=200, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="name_ru",
            field=models.CharField(
                max_length=200, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_tags",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_tags_de",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_tags_en",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_tags_ru",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_de",
            field=models.CharField(
                max_length=200, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_en",
            field=models.CharField(
                max_length=200, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_ru",
            field=models.CharField(
                max_length=200, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="meta_tags",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="meta_tags_de",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="meta_tags_en",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="meta_tags_ru",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="name_de",
            field=models.CharField(
                max_length=200, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="name_en",
            field=models.CharField(
                max_length=200, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="name_ru",
            field=models.CharField(
                max_length=200, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="meta_tags",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="meta_tags_de",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="meta_tags_en",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="meta_tags_ru",
            field=models.TextField(
                default='<title>BlumenHorizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="name_de",
            field=models.CharField(
                max_length=200, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="name_en",
            field=models.CharField(
                max_length=200, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="name_ru",
            field=models.CharField(
                max_length=200, null=True, unique=True, verbose_name="Название"
            ),
        ),
    ]
