# Generated by Django 5.1.3 on 2024-11-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0044_alter_bouquet_json_ld_alter_bouquet_meta_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bouquet",
            name="slug",
            field=models.SlugField(
                max_length=80, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AlterField(
            model_name="bouquet",
            name="slug_de",
            field=models.SlugField(
                max_length=80, null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AlterField(
            model_name="bouquet",
            name="slug_en",
            field=models.SlugField(
                max_length=80, null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AlterField(
            model_name="bouquet",
            name="slug_ru",
            field=models.SlugField(
                max_length=80, null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="slug",
            field=models.SlugField(
                max_length=80, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="slug_de",
            field=models.SlugField(
                max_length=80, null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="slug_en",
            field=models.SlugField(
                max_length=80, null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="slug_ru",
            field=models.SlugField(
                max_length=80, null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="slug",
            field=models.SlugField(
                max_length=80, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="slug_de",
            field=models.SlugField(
                max_length=80, null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="slug_en",
            field=models.SlugField(
                max_length=80, null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="slug_ru",
            field=models.SlugField(
                max_length=80, null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                max_length=80, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug_de",
            field=models.SlugField(
                max_length=80, null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug_en",
            field=models.SlugField(
                max_length=80, null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug_ru",
            field=models.SlugField(
                max_length=80, null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="slug",
            field=models.SlugField(
                max_length=80, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="slug_de",
            field=models.SlugField(
                max_length=80, null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="slug_en",
            field=models.SlugField(
                max_length=80, null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="slug_ru",
            field=models.SlugField(
                max_length=80, null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="slug",
            field=models.SlugField(
                max_length=80, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="slug_de",
            field=models.SlugField(
                max_length=80, null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="slug_en",
            field=models.SlugField(
                max_length=80, null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="slug_ru",
            field=models.SlugField(
                max_length=80, null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
    ]
