# Generated by Django 5.1.3 on 2024-11-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0045_alter_bouquet_slug_alter_bouquet_slug_de_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bouquetcategory",
            name="image_alt",
            field=models.CharField(max_length=200, verbose_name="Описание картинки"),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="image_alt_de",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="image_alt_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="image_alt_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetimage",
            name="image_alt",
            field=models.CharField(max_length=200, verbose_name="Описание картинки"),
        ),
        migrations.AlterField(
            model_name="bouquetimage",
            name="image_alt_de",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetimage",
            name="image_alt_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetimage",
            name="image_alt_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsizeimage",
            name="image_alt",
            field=models.CharField(max_length=200, verbose_name="Описание картинки"),
        ),
        migrations.AlterField(
            model_name="bouquetsizeimage",
            name="image_alt_de",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsizeimage",
            name="image_alt_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsizeimage",
            name="image_alt_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="image_alt",
            field=models.CharField(max_length=200, verbose_name="Описание картинки"),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="image_alt_de",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="image_alt_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="image_alt_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="image_alt",
            field=models.CharField(max_length=200, verbose_name="Описание картинки"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="image_alt_de",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="image_alt_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="image_alt_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_alt",
            field=models.CharField(max_length=200, verbose_name="Описание картинки"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_alt_de",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_alt_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_alt_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="image_alt",
            field=models.CharField(max_length=200, verbose_name="Описание картинки"),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="image_alt_de",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="image_alt_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="image_alt_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
    ]
