# Generated by Django 5.1.3 on 2024-11-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0046_alter_bouquetcategory_image_alt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bouquetslistpagemodel",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="catalogpagemodel",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="productslistpagemodel",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                verbose_name="JSON-LD",
            ),
        ),
    ]
