# Generated by Django 5.1.3 on 2024-11-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0046_alter_bouquetcategory_image_alt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bouquet",
            name="json_ld_de",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="bouquet",
            name="json_ld_en",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="bouquet",
            name="json_ld_ru",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="bouquetcategory",
            name="json_ld_de",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="bouquetcategory",
            name="json_ld_en",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="bouquetcategory",
            name="json_ld_ru",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="bouquetsubcategory",
            name="json_ld_de",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="bouquetsubcategory",
            name="json_ld_en",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="bouquetsubcategory",
            name="json_ld_ru",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="catalogpagemodel",
            name="json_ld_de",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=1000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="catalogpagemodel",
            name="json_ld_en",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=1000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="catalogpagemodel",
            name="json_ld_ru",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=1000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="json_ld_de",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="json_ld_en",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="json_ld_ru",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="json_ld_de",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="json_ld_en",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="json_ld_ru",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="json_ld_de",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="json_ld_en",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="json_ld_ru",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
    ]
