# Generated by Django 5.1.3 on 2024-11-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0047_bouquet_json_ld_de_bouquet_json_ld_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bouquet",
            name="json_ld_de",
        ),
        migrations.RemoveField(
            model_name="bouquet",
            name="json_ld_en",
        ),
        migrations.RemoveField(
            model_name="bouquet",
            name="json_ld_ru",
        ),
        migrations.RemoveField(
            model_name="bouquetcategory",
            name="json_ld_de",
        ),
        migrations.RemoveField(
            model_name="bouquetcategory",
            name="json_ld_en",
        ),
        migrations.RemoveField(
            model_name="bouquetcategory",
            name="json_ld_ru",
        ),
        migrations.RemoveField(
            model_name="bouquetsubcategory",
            name="json_ld_de",
        ),
        migrations.RemoveField(
            model_name="bouquetsubcategory",
            name="json_ld_en",
        ),
        migrations.RemoveField(
            model_name="bouquetsubcategory",
            name="json_ld_ru",
        ),
        migrations.RemoveField(
            model_name="catalogpagemodel",
            name="json_ld_de",
        ),
        migrations.RemoveField(
            model_name="catalogpagemodel",
            name="json_ld_en",
        ),
        migrations.RemoveField(
            model_name="catalogpagemodel",
            name="json_ld_ru",
        ),
        migrations.RemoveField(
            model_name="product",
            name="json_ld_de",
        ),
        migrations.RemoveField(
            model_name="product",
            name="json_ld_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="json_ld_ru",
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="json_ld_de",
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="json_ld_en",
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="json_ld_ru",
        ),
        migrations.RemoveField(
            model_name="productsubcategory",
            name="json_ld_de",
        ),
        migrations.RemoveField(
            model_name="productsubcategory",
            name="json_ld_en",
        ),
        migrations.RemoveField(
            model_name="productsubcategory",
            name="json_ld_ru",
        ),
        migrations.AlterField(
            model_name="bouquetslistpagemodel",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="catalogpagemodel",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="productslistpagemodel",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=4000,
                verbose_name="JSON-LD",
            ),
        ),
    ]
