# Generated by Django 5.1.3 on 2024-11-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogue",
            "0048_alter_bouquet_meta_tags_alter_bouquet_meta_tags_de_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bouquetcategory",
            name="catalog_page_meta_tags",
            field=models.TextField(
                default='<title>Blumen Horizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                verbose_name="Мета-теги на странице категории со списком подкатегорий",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="catalog_page_meta_tags",
            field=models.TextField(
                default='<title>Blumen Horizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                verbose_name="Мета-теги на странице категории со списком подкатегорий",
            ),
        ),
    ]
