# Generated by Django 5.1.3 on 2024-11-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0049_bouquetcategory_catalog_page_meta_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bouquetcategory",
            name="catalog_page_meta_tags_de",
            field=models.TextField(
                default='<title>Blumen Horizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги на странице категории со списком подкатегорий",
            ),
        ),
        migrations.AddField(
            model_name="bouquetcategory",
            name="catalog_page_meta_tags_en",
            field=models.TextField(
                default='<title>Blumen Horizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги на странице категории со списком подкатегорий",
            ),
        ),
        migrations.AddField(
            model_name="bouquetcategory",
            name="catalog_page_meta_tags_ru",
            field=models.TextField(
                default='<title>Blumen Horizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги на странице категории со списком подкатегорий",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="catalog_page_meta_tags_de",
            field=models.TextField(
                default='<title>Blumen Horizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги на странице категории со списком подкатегорий",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="catalog_page_meta_tags_en",
            field=models.TextField(
                default='<title>Blumen Horizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги на странице категории со списком подкатегорий",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="catalog_page_meta_tags_ru",
            field=models.TextField(
                default='<title>Blumen Horizon | </title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги на странице категории со списком подкатегорий",
            ),
        ),
    ]
