# Generated by Django 5.1.3 on 2024-11-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogue",
            "0048_remove_bouquet_json_ld_de_remove_bouquet_json_ld_en_and_more",
        ),
        (
            "catalogue",
            "0049_remove_bouquet_json_ld_de_remove_bouquet_json_ld_en_and_more",
        ),
    ]

    operations = []
