# Generated by Django 5.1.3 on 2024-12-05 16:42

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0052_rename_description_ua_bouquet_description_uk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogpagemodel",
            name="description",
            field=tinymce.models.HTMLField(default="", verbose_name="Описание"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="catalogpagemodel",
            name="description_de",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="catalogpagemodel",
            name="description_en",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="catalogpagemodel",
            name="description_ru",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="catalogpagemodel",
            name="description_uk",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
    ]
