# Generated by Django 5.1.3 on 2024-12-05 19:28

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0053_catalogpagemodel_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catalogpagemodel",
            options={
                "verbose_name": "Страница 'Каталог'",
                "verbose_name_plural": "Страница 'Каталог'",
            },
        ),
        migrations.AddField(
            model_name="bouquetcategory",
            name="description",
            field=tinymce.models.HTMLField(
                null=True, verbose_name="Описание на странице категории"
            ),
        ),
        migrations.AddField(
            model_name="bouquetcategory",
            name="description_de",
            field=tinymce.models.HTMLField(
                null=True, verbose_name="Описание на странице категории"
            ),
        ),
        migrations.AddField(
            model_name="bouquetcategory",
            name="description_en",
            field=tinymce.models.HTMLField(
                null=True, verbose_name="Описание на странице категории"
            ),
        ),
        migrations.AddField(
            model_name="bouquetcategory",
            name="description_ru",
            field=tinymce.models.HTMLField(
                null=True, verbose_name="Описание на странице категории"
            ),
        ),
        migrations.AddField(
            model_name="bouquetcategory",
            name="description_uk",
            field=tinymce.models.HTMLField(
                null=True, verbose_name="Описание на странице категории"
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="description",
            field=tinymce.models.HTMLField(
                null=True, verbose_name="Описание на странице категории"
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="description_de",
            field=tinymce.models.HTMLField(
                null=True, verbose_name="Описание на странице категории"
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="description_en",
            field=tinymce.models.HTMLField(
                null=True, verbose_name="Описание на странице категории"
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="description_ru",
            field=tinymce.models.HTMLField(
                null=True, verbose_name="Описание на странице категории"
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="description_uk",
            field=tinymce.models.HTMLField(
                null=True, verbose_name="Описание на странице категории"
            ),
        ),
        migrations.AlterField(
            model_name="catalogpagemodel",
            name="description",
            field=tinymce.models.HTMLField(
                null=True, verbose_name="Описание на странице 'Каталог'"
            ),
        ),
        migrations.AlterField(
            model_name="catalogpagemodel",
            name="description_de",
            field=tinymce.models.HTMLField(
                null=True, verbose_name="Описание на странице 'Каталог'"
            ),
        ),
        migrations.AlterField(
            model_name="catalogpagemodel",
            name="description_en",
            field=tinymce.models.HTMLField(
                null=True, verbose_name="Описание на странице 'Каталог'"
            ),
        ),
        migrations.AlterField(
            model_name="catalogpagemodel",
            name="description_ru",
            field=tinymce.models.HTMLField(
                null=True, verbose_name="Описание на странице 'Каталог'"
            ),
        ),
        migrations.AlterField(
            model_name="catalogpagemodel",
            name="description_uk",
            field=tinymce.models.HTMLField(
                null=True, verbose_name="Описание на странице 'Каталог'"
            ),
        ),
    ]
