# Generated by Django 5.1.4 on 2024-12-16 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0054_alter_catalogpagemodel_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bouquet",
            options={"verbose_name": "Букет", "verbose_name_plural": "1. Букеты"},
        ),
        migrations.AlterModelOptions(
            name="bouquetcategory",
            options={
                "verbose_name": "Категория букета",
                "verbose_name_plural": "4. Категории букетов",
            },
        ),
        migrations.AlterModelOptions(
            name="bouquetsubcategory",
            options={
                "verbose_name": "Подкатегория букета",
                "verbose_name_plural": "5. Подкатегории букетов",
            },
        ),
        migrations.AlterModelOptions(
            name="catalogpagemodel",
            options={
                "verbose_name": "Страница «Каталог»",
                "verbose_name_plural": "Страница «Каталог»",
            },
        ),
        migrations.AlterModelOptions(
            name="color",
            options={
                "verbose_name": "Цвет букета",
                "verbose_name_plural": "3. Цветовые гаммы букетов",
            },
        ),
        migrations.AlterModelOptions(
            name="flower",
            options={
                "verbose_name": "Цветок",
                "verbose_name_plural": "2. Состав букетов",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "6. Продукты"},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={
                "verbose_name": "Категория продукта",
                "verbose_name_plural": "7. Категории продуктов",
            },
        ),
        migrations.AlterModelOptions(
            name="productsubcategory",
            options={
                "verbose_name": "Подкатегория продукта",
                "verbose_name_plural": "8. Подкатегории продуктов",
            },
        ),
    ]
