# Generated by Django 5.1.4 on 2024-12-20 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogue",
            "0055_alter_bouquet_options_alter_bouquetcategory_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bouquet",
            name="json_ld",
        ),
        migrations.RemoveField(
            model_name="bouquetcategory",
            name="json_ld",
        ),
        migrations.RemoveField(
            model_name="bouquetslistpagemodel",
            name="json_ld",
        ),
        migrations.RemoveField(
            model_name="bouquetsubcategory",
            name="json_ld",
        ),
        migrations.RemoveField(
            model_name="catalogpagemodel",
            name="json_ld",
        ),
        migrations.RemoveField(
            model_name="product",
            name="json_ld",
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="json_ld",
        ),
        migrations.RemoveField(
            model_name="productslistpagemodel",
            name="json_ld",
        ),
        migrations.RemoveField(
            model_name="productsubcategory",
            name="json_ld",
        ),
    ]
