# Generated by Django 5.1.4 on 2024-12-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0056_remove_bouquet_json_ld_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bouquetimage",
            old_name="bouquet",
            new_name="item",
        ),
        migrations.RenameField(
            model_name="productimage",
            old_name="product",
            new_name="item",
        ),
        migrations.AlterField(
            model_name="bouquet",
            name="meta_tags",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquet",
            name="meta_tags_de",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquet",
            name="meta_tags_en",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquet",
            name="meta_tags_ru",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquet",
            name="meta_tags_uk",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="catalog_page_meta_tags",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                verbose_name="Мета-теги на странице категории со списком подкатегорий",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="catalog_page_meta_tags_de",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги на странице категории со списком подкатегорий",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="catalog_page_meta_tags_en",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги на странице категории со списком подкатегорий",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="catalog_page_meta_tags_ru",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги на странице категории со списком подкатегорий",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="catalog_page_meta_tags_uk",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги на странице категории со списком подкатегорий",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="meta_tags",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="meta_tags_de",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="meta_tags_en",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="meta_tags_ru",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetcategory",
            name="meta_tags_uk",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetslistpagemodel",
            name="meta_tags",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=1000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetslistpagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetslistpagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetslistpagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetslistpagemodel",
            name="meta_tags_uk",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="meta_tags",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="meta_tags_de",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="meta_tags_en",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="meta_tags_ru",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="bouquetsubcategory",
            name="meta_tags_uk",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="catalogpagemodel",
            name="meta_tags",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=1000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="catalogpagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="catalogpagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="catalogpagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="catalogpagemodel",
            name="meta_tags_uk",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_tags",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_tags_de",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_tags_en",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_tags_ru",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_tags_uk",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="catalog_page_meta_tags",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                verbose_name="Мета-теги на странице категории со списком подкатегорий",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="catalog_page_meta_tags_de",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги на странице категории со списком подкатегорий",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="catalog_page_meta_tags_en",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги на странице категории со списком подкатегорий",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="catalog_page_meta_tags_ru",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги на странице категории со списком подкатегорий",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="catalog_page_meta_tags_uk",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги на странице категории со списком подкатегорий",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="meta_tags",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="meta_tags_de",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="meta_tags_en",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="meta_tags_ru",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="meta_tags_uk",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="productslistpagemodel",
            name="meta_tags",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=1000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="productslistpagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="productslistpagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="productslistpagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="productslistpagemodel",
            name="meta_tags_uk",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="meta_tags",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="meta_tags_de",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="meta_tags_en",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="meta_tags_ru",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="meta_tags_uk",
            field=models.TextField(
                default='<title> | BlumenHorizon</title>\n<meta name="description" content="Описание">',
                max_length=4000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
    ]
