# Generated by Django 5.1.4 on 2025-01-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0058_bouquetreview_productreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bouquetreview",
            name="author_name",
            field=models.CharField(
                default="Аноним", max_length=80, verbose_name="Имя автора"
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="author_name",
            field=models.CharField(
                default="Аноним", max_length=80, verbose_name="Имя автора"
            ),
        ),
    ]
