# Generated by Django 5.1.4 on 2025-01-27 22:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0058_itemreview_bouquetreview_productreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemreview",
            name="rate",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Рейтинг",
            ),
        ),
    ]
