# Generated by Django 5.1.4 on 2025-01-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0059_alter_bouquetreview_author_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bouquetreview",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
    ]
