# Generated by Django 5.1.4 on 2025-01-30 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0060_alter_bouquetreview_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bouquet",
            name="discount",
            field=models.IntegerField(
                default=0,
                help_text="Будет рассчитано после налога",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Скидка",
            ),
        ),
        migrations.AlterField(
            model_name="bouquet",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Цена продукта без налога до 10ти значений, два из которых плавающая запятая. Т.е. до 99999999.99",
                max_digits=10,
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.IntegerField(
                default=0,
                help_text="Будет рассчитано после налога",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Скидка",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Цена продукта без налога до 10ти значений, два из которых плавающая запятая. Т.е. до 99999999.99",
                max_digits=10,
                verbose_name="Цена",
            ),
        ),
    ]
