# Generated by Django 5.1.4 on 2025-01-28 19:00

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0060_alter_itemreview_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productreview",
            name="itemreview_ptr",
        ),
        migrations.RemoveField(
            model_name="bouquetreview",
            name="itemreview_ptr",
        ),
        migrations.AlterModelOptions(
            name="bouquetreview",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.AlterModelOptions(
            name="productreview",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.AddField(
            model_name="bouquetreview",
            name="author_name",
            field=models.CharField(
                default="", max_length=80, verbose_name="Имя автора"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bouquetreview",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bouquetreview",
            name="description",
            field=models.TextField(default="", verbose_name="Описание"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bouquetreview",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email автора"
            ),
        ),
        migrations.AddField(
            model_name="bouquetreview",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bouquetreview",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Прошло модерацию?"),
        ),
        migrations.AddField(
            model_name="bouquetreview",
            name="rate",
            field=models.IntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Рейтинг",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bouquetreview",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AddField(
            model_name="productreview",
            name="author_name",
            field=models.CharField(
                default="", max_length=80, verbose_name="Имя автора"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productreview",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productreview",
            name="description",
            field=models.TextField(default="", verbose_name="Описание"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productreview",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email автора"
            ),
        ),
        migrations.AddField(
            model_name="productreview",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productreview",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Прошло модерацию?"),
        ),
        migrations.AddField(
            model_name="productreview",
            name="rate",
            field=models.IntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Рейтинг",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productreview",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.DeleteModel(
            name="ItemReview",
        ),
    ]
