# Generated by Django 5.1.4 on 2025-02-02 17:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

def create_taxes(apps, schema_editor):
    TaxPercent = apps.get_model("catalogue", "TaxPercent")

    TaxPercent.objects.create(value=7, stripe_id = "txr_1Qo2Z6KoL7GYbzW5MUO9oPjd")
    TaxPercent.objects.create(value=19, stripe_id = "txr_1Qo2ZcKoL7GYbzW5N8WZgRBA")


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0061_alter_bouquet_discount_alter_bouquet_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxPercent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "value",
                    models.IntegerField(
                        default=7,
                        help_text="Рассчитывается после начисления налога",
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="НДС",
                    ),
                ),
                (
                    "stripe_id",
                    models.CharField(
                        blank=True,
                        help_text="Нужно запросить у нашего администратора Stripe",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="ID налога в Stripe",
                    ),
                ),
            ],
            options={
                "verbose_name": "НАЛОГ НДС",
                "verbose_name_plural": "НАЛОГИ НДС",
            },
        ),
        migrations.RunPython(create_taxes),
        migrations.AddField(
            model_name="bouquet",
            name="tax_percent",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите налоговую ставку, применимую к данному букету. Вычисляется до скидки.",
                null=True,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bouquets",
                to="catalogue.taxpercent",
                verbose_name="Налоговая ставка",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tax_percent",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите налоговую ставку, применимую к данному товару. Вычисляется до скидки.",
                null=True,
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalogue.taxpercent",
                verbose_name="Налоговая ставка",
            ),
        ),
    ]
