# Generated by Django 5.1.4 on 2025-02-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0062_taxpercent_bouquet_tax_percent_product_tax_percent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bouquet",
            name="tax_percent",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tax_percent",
        ),
    ]
