# Generated by Django 5.1.4 on 2025-02-04 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0062_taxpercent_bouquet_tax_percent_product_tax_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bouquet",
            name="tax_percent",
            field=models.ForeignKey(
                blank=True,
                default=1,
                help_text="Выберите налоговую ставку, применимую к данному букету. Вычисляется после скидки.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bouquets",
                to="catalogue.taxpercent",
                verbose_name="Налоговая ставка",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tax_percent",
            field=models.ForeignKey(
                blank=True,
                default=2,
                help_text="Выберите налоговую ставку, применимую к данному товару. Вычисляется после скидки.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalogue.taxpercent",
                verbose_name="Налоговая ставка",
            ),
        ),
    ]
