# Generated by Django 5.1.4 on 2025-02-01 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0063_remove_bouquet_tax_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bouquet",
            name="tax_percent",
            field=models.ForeignKey(
                blank=True,
                default=1,
                help_text="Выберите налоговую ставку, применимую к данному букету. Вычисляется до скидки.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bouquets",
                to="catalogue.taxpercent",
                verbose_name="Налоговая ставка",
            ),
        ),
    ]
