# Generated by Django 5.1.4 on 2025-02-01 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0064_bouquet_tax_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tax_percent",
            field=models.ForeignKey(
                blank=True,
                default=2,
                help_text="Выберите налоговую ставку, применимую к данному товару. Вычисляется до скидки.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalogue.taxpercent",
                verbose_name="Налоговая ставка",
            ),
        ),
    ]
