# Generated by Django 5.1.4 on 2025-02-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0065_product_tax_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxpercent",
            name="stripe_id",
            field=models.CharField(
                blank=True,
                help_text="Нужно запросить у нашего администратора Stripe",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="ID налога в Stripe",
            ),
        ),
    ]
