# Generated by Django 5.1.4 on 2025-02-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0066_taxpercent_stripe_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taxpercent",
            options={"verbose_name": "НАЛОГ НДС", "verbose_name_plural": "НАЛОГИ НДС"},
        ),
    ]
