# Generated by Django 5.1.2 on 2024-11-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MainPageSliderImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="", verbose_name="Фото на главном слайде"
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
