# Generated by Django 5.1.2 on 2024-11-01 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mainpagesliderimages",
            options={
                "verbose_name": "Фото слайдера главной страницы",
                "verbose_name_plural": "Фотографии слайдера главной страницы",
            },
        ),
    ]
