# Generated by Django 5.1.2 on 2024-11-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0002_alter_mainpagesliderimages_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainpagesliderimages",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активное?"),
        ),
    ]
