# Generated by Django 5.1.2 on 2024-11-06 16:55

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0003_alter_mainpagesliderimages_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndividualOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=40)),
                (
                    "phonenumber",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=15,
                        null=True,
                        region=None,
                        unique=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individual_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Связанный аккаунт",
                    ),
                ),
            ],
        ),
    ]
