# Generated by Django 5.1.2 on 2024-11-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0004_individualorder"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeoBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="defaults/no-image.webp",
                        upload_to="seoblock/",
                        verbose_name="Картинка",
                    ),
                ),
            ],
        ),
    ]
