# Generated by Django 5.1.2 on 2024-11-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0005_seoblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="seoblock",
            name="alt",
            field=models.CharField(
                default="", max_length=40, verbose_name="Описание картинки"
            ),
            preserve_default=False,
        ),
    ]
