# Generated by Django 5.1.2 on 2024-11-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0006_seoblock_alt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seoblock",
            options={"verbose_name": "СЕО Блок", "verbose_name_plural": "СЕО Блоки"},
        ),
        migrations.AddField(
            model_name="individualorder",
            name="recall_me",
            field=models.BooleanField(
                default=False, verbose_name="Разрешил ли пользователь звонить ему"
            ),
        ),
    ]
