# Generated by Django 5.1.2 on 2024-11-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0008_alter_individualorder_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individualorder",
            name="first_name",
            field=models.CharField(max_length=40, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="individualorder",
            name="recall_me",
            field=models.BooleanField(
                default=False, verbose_name="Разрешил ли клиент звонить ему"
            ),
        ),
    ]
