# Generated by Django 5.1.2 on 2024-11-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0009_alter_individualorder_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="individualorder",
            name="phonenumber",
        ),
        migrations.AddField(
            model_name="individualorder",
            name="contact_method",
            field=models.TextField(
                default="A", max_length=100, verbose_name="Способ связи с клиентом"
            ),
            preserve_default=False,
        ),
    ]
