# Generated by Django 5.1.2 on 2024-11-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0010_remove_individualorder_phonenumber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainpagesliderimages",
            name="image",
            field=models.ImageField(
                upload_to="mainpage-slider/", verbose_name="Фото на главном слайде"
            ),
        ),
        migrations.AlterField(
            model_name="seoblock",
            name="image",
            field=models.ImageField(upload_to="seoblock/", verbose_name="Картинка"),
        ),
    ]
