# Generated by Django 5.1.2 on 2024-11-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0012_seoblock_created_at_seoblock_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpagesliderimages",
            name="image_alt",
            field=models.CharField(
                default="", max_length=100, verbose_name="Описание картинки"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mainpagesliderimages",
            name="image_alt_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="mainpagesliderimages",
            name="image_alt_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="seoblock",
            name="image_alt",
            field=models.CharField(
                default="", max_length=100, verbose_name="Описание картинки"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seoblock",
            name="image_alt_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="seoblock",
            name="image_alt_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
    ]
