# Generated by Django 5.1.2 on 2024-11-13 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0013_mainpagesliderimages_image_alt_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seoblock",
            name="alt",
        ),
    ]
