# Generated by Django 5.1.2 on 2024-11-14 14:05

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0016_alter_individualorder_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainPageMetaTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_tags", tinymce.models.HTMLField(verbose_name="Мета-теги")),
            ],
        ),
    ]
