# Generated by Django 5.1.2 on 2024-11-14 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0017_mainpagemetatags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mainpagemetatags",
            options={
                "verbose_name": "Мета-тег главной страницы",
                "verbose_name_plural": "Мета-теги главной страницы",
            },
        ),
    ]
