# Generated by Django 5.1.2 on 2024-11-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0020_alter_mainpagemetatags_meta_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpagemetatags",
            name="meta_tags_en",
            field=models.TextField(
                default="<title>BlumenHorizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AddField(
            model_name="mainpagemetatags",
            name="meta_tags_ru",
            field=models.TextField(
                default="<title>BlumenHorizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
    ]
