# Generated by Django 5.1.2 on 2024-11-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0021_mainpagemetatags_meta_tags_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainPageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_tags",
                    models.TextField(
                        default="<title>BlumenHorizon | </title>",
                        max_length=1000,
                        verbose_name="Мета-теги",
                    ),
                ),
                (
                    "meta_tags_ru",
                    models.TextField(
                        default="<title>BlumenHorizon | </title>",
                        max_length=1000,
                        null=True,
                        verbose_name="Мета-теги",
                    ),
                ),
                (
                    "meta_tags_en",
                    models.TextField(
                        default="<title>BlumenHorizon | </title>",
                        max_length=1000,
                        null=True,
                        verbose_name="Мета-теги",
                    ),
                ),
                (
                    "json_ld",
                    models.TextField(
                        default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                        max_length=1000,
                        verbose_name="JSON-LD",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мета-тег главной страницы",
                "verbose_name_plural": "Мета-теги главной страницы",
            },
        ),
        migrations.DeleteModel(
            name="MainPageMetaTags",
        ),
    ]
