# Generated by Django 5.1.3 on 2024-11-20 17:15

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0023_alter_mainpagemodel_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUsPageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="seoblock/", verbose_name="Картинка"),
                ),
                (
                    "image_alt",
                    models.CharField(max_length=100, verbose_name="Описание картинки"),
                ),
                ("description", tinymce.models.HTMLField(verbose_name="Описание")),
                (
                    "meta_tags",
                    models.TextField(
                        default="<title>BlumenHorizon | </title>",
                        max_length=1000,
                        verbose_name="Мета-теги",
                    ),
                ),
                (
                    "json_ld",
                    models.TextField(
                        default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                        max_length=1000,
                        verbose_name="JSON-LD",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactsPageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="seoblock/", verbose_name="Картинка"),
                ),
                (
                    "image_alt",
                    models.CharField(max_length=100, verbose_name="Описание картинки"),
                ),
                ("description", tinymce.models.HTMLField(verbose_name="Описание")),
                (
                    "meta_tags",
                    models.TextField(
                        default="<title>BlumenHorizon | </title>",
                        max_length=1000,
                        verbose_name="Мета-теги",
                    ),
                ),
                (
                    "json_ld",
                    models.TextField(
                        default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                        max_length=1000,
                        verbose_name="JSON-LD",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeliveryPageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="seoblock/", verbose_name="Картинка"),
                ),
                (
                    "image_alt",
                    models.CharField(max_length=100, verbose_name="Описание картинки"),
                ),
                ("description", tinymce.models.HTMLField(verbose_name="Описание")),
                (
                    "meta_tags",
                    models.TextField(
                        default="<title>BlumenHorizon | </title>",
                        max_length=1000,
                        verbose_name="Мета-теги",
                    ),
                ),
                (
                    "json_ld",
                    models.TextField(
                        default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                        max_length=1000,
                        verbose_name="JSON-LD",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FAQPageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="seoblock/", verbose_name="Картинка"),
                ),
                (
                    "image_alt",
                    models.CharField(max_length=100, verbose_name="Описание картинки"),
                ),
                ("description", tinymce.models.HTMLField(verbose_name="Описание")),
                (
                    "meta_tags",
                    models.TextField(
                        default="<title>BlumenHorizon | </title>",
                        max_length=1000,
                        verbose_name="Мета-теги",
                    ),
                ),
                (
                    "json_ld",
                    models.TextField(
                        default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                        max_length=1000,
                        verbose_name="JSON-LD",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameModel(
            old_name="SeoBlock",
            new_name="MainPageSeoBlock",
        ),
    ]
