# Generated by Django 5.1.3 on 2024-11-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mainpage",
            "0024_aboutuspagemodel_contactspagemodel_deliverypagemodel_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutuspagemodel",
            options={"verbose_name": "О нас", "verbose_name_plural": "О нас"},
        ),
        migrations.AlterModelOptions(
            name="contactspagemodel",
            options={"verbose_name": "Контакты", "verbose_name_plural": "Контакты"},
        ),
        migrations.AlterModelOptions(
            name="deliverypagemodel",
            options={"verbose_name": "Доставка", "verbose_name_plural": "Доставка"},
        ),
        migrations.AlterModelOptions(
            name="faqpagemodel",
            options={
                "verbose_name": "Частозадаваемые вопросы",
                "verbose_name_plural": "Частозадаваемые вопросы",
            },
        ),
        migrations.AlterField(
            model_name="aboutuspagemodel",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=1000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="contactspagemodel",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=1000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="deliverypagemodel",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=1000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="faqpagemodel",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=1000,
                verbose_name="JSON-LD",
            ),
        ),
    ]
