# Generated by Django 5.1.3 on 2024-11-20 17:23

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0025_alter_aboutuspagemodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutuspagemodel",
            name="description_en",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="aboutuspagemodel",
            name="description_ru",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="aboutuspagemodel",
            name="image_alt_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="aboutuspagemodel",
            name="image_alt_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="aboutuspagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default="<title>BlumenHorizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AddField(
            model_name="aboutuspagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default="<title>BlumenHorizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AddField(
            model_name="contactspagemodel",
            name="description_en",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="contactspagemodel",
            name="description_ru",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="contactspagemodel",
            name="image_alt_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="contactspagemodel",
            name="image_alt_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="contactspagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default="<title>BlumenHorizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AddField(
            model_name="contactspagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default="<title>BlumenHorizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AddField(
            model_name="deliverypagemodel",
            name="description_en",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="deliverypagemodel",
            name="description_ru",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="deliverypagemodel",
            name="image_alt_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="deliverypagemodel",
            name="image_alt_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="deliverypagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default="<title>BlumenHorizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AddField(
            model_name="deliverypagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default="<title>BlumenHorizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AddField(
            model_name="faqpagemodel",
            name="description_en",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="faqpagemodel",
            name="description_ru",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="faqpagemodel",
            name="image_alt_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="faqpagemodel",
            name="image_alt_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="faqpagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default="<title>BlumenHorizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AddField(
            model_name="faqpagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default="<title>BlumenHorizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
    ]
