# Generated by Django 5.1.3 on 2024-11-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0027_remove_deliverypagemodel_meta_tags_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverypagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default="<title>BlumenHorizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AddField(
            model_name="deliverypagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default="<title>BlumenHorizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
    ]
