# Generated by Django 5.1.3 on 2024-11-20 18:08

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0028_deliverypagemodel_meta_tags_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpagemodel",
            name="description",
            field=tinymce.models.HTMLField(default="", verbose_name="Описание"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mainpagemodel",
            name="description_en",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="mainpagemodel",
            name="description_ru",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="aboutuspagemodel",
            name="image",
            field=models.ImageField(
                default="defaults/no-image.webp",
                upload_to="seoblock/",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="contactspagemodel",
            name="image",
            field=models.ImageField(
                default="defaults/no-image.webp",
                upload_to="seoblock/",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="deliverypagemodel",
            name="image",
            field=models.ImageField(
                default="defaults/no-image.webp",
                upload_to="seoblock/",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="faqpagemodel",
            name="image",
            field=models.ImageField(
                default="defaults/no-image.webp",
                upload_to="seoblock/",
                verbose_name="Картинка",
            ),
        ),
    ]
