# Generated by Django 5.1.3 on 2024-11-22 03:51

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0029_mainpagemodel_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutuspagemodel",
            name="description_de",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="aboutuspagemodel",
            name="image_alt_de",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="aboutuspagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default="<title>BlumenHorizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AddField(
            model_name="contactspagemodel",
            name="description_de",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="contactspagemodel",
            name="image_alt_de",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="contactspagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default="<title>BlumenHorizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AddField(
            model_name="deliverypagemodel",
            name="description_de",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="deliverypagemodel",
            name="image_alt_de",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="deliverypagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default="<title>BlumenHorizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AddField(
            model_name="faqpagemodel",
            name="description_de",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="faqpagemodel",
            name="image_alt_de",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="faqpagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default="<title>BlumenHorizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AddField(
            model_name="mainpagemodel",
            name="description_de",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="mainpagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default="<title>BlumenHorizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AddField(
            model_name="mainpageseoblock",
            name="image_alt_de",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AddField(
            model_name="mainpagesliderimages",
            name="image_alt_de",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Описание картинки"
            ),
        ),
    ]
