# Generated by Django 5.1.3 on 2024-11-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0031_alter_aboutuspagemodel_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutuspagemodel",
            name="image_alt",
            field=models.CharField(max_length=200, verbose_name="Описание картинки"),
        ),
        migrations.AlterField(
            model_name="aboutuspagemodel",
            name="image_alt_de",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="aboutuspagemodel",
            name="image_alt_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="aboutuspagemodel",
            name="image_alt_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="contactspagemodel",
            name="image_alt",
            field=models.CharField(max_length=200, verbose_name="Описание картинки"),
        ),
        migrations.AlterField(
            model_name="contactspagemodel",
            name="image_alt_de",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="contactspagemodel",
            name="image_alt_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="contactspagemodel",
            name="image_alt_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="deliverypagemodel",
            name="image_alt",
            field=models.CharField(max_length=200, verbose_name="Описание картинки"),
        ),
        migrations.AlterField(
            model_name="deliverypagemodel",
            name="image_alt_de",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="deliverypagemodel",
            name="image_alt_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="deliverypagemodel",
            name="image_alt_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="faqpagemodel",
            name="image_alt",
            field=models.CharField(max_length=200, verbose_name="Описание картинки"),
        ),
        migrations.AlterField(
            model_name="faqpagemodel",
            name="image_alt_de",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="faqpagemodel",
            name="image_alt_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="faqpagemodel",
            name="image_alt_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="mainpageseoblock",
            name="image_alt",
            field=models.CharField(max_length=200, verbose_name="Описание картинки"),
        ),
        migrations.AlterField(
            model_name="mainpageseoblock",
            name="image_alt_de",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="mainpageseoblock",
            name="image_alt_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="mainpageseoblock",
            name="image_alt_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="mainpagesliderimages",
            name="image_alt",
            field=models.CharField(max_length=200, verbose_name="Описание картинки"),
        ),
        migrations.AlterField(
            model_name="mainpagesliderimages",
            name="image_alt_de",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="mainpagesliderimages",
            name="image_alt_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="mainpagesliderimages",
            name="image_alt_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Описание картинки"
            ),
        ),
    ]
