# Generated by Django 5.1.3 on 2024-11-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mainpage",
            "0033_aboutuspagemodel_image_de_aboutuspagemodel_image_en_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faqpagemodel",
            options={
                "verbose_name": "Часто задаваемые вопросы",
                "verbose_name_plural": "Часто задаваемые вопросы",
            },
        ),
    ]
