# Generated by Django 5.1.3 on 2024-11-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0034_alter_faqpagemodel_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutuspagemodel",
            name="json_ld_de",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=1000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="aboutuspagemodel",
            name="json_ld_en",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=1000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="aboutuspagemodel",
            name="json_ld_ru",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=1000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="contactspagemodel",
            name="json_ld_de",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=1000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="contactspagemodel",
            name="json_ld_en",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=1000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="contactspagemodel",
            name="json_ld_ru",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=1000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="deliverypagemodel",
            name="json_ld_de",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=1000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="deliverypagemodel",
            name="json_ld_en",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=1000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="deliverypagemodel",
            name="json_ld_ru",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=1000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="faqpagemodel",
            name="json_ld_de",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=1000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="faqpagemodel",
            name="json_ld_en",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=1000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="faqpagemodel",
            name="json_ld_ru",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=1000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="mainpagemodel",
            name="json_ld_de",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=1000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="mainpagemodel",
            name="json_ld_en",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=1000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="mainpagemodel",
            name="json_ld_ru",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n        </script>',
                max_length=1000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
    ]
