# Generated by Django 5.1.3 on 2024-11-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0035_remove_mainpagemodel_json_ld_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpagemodel",
            name="json_ld_description_de",
            field=models.CharField(
                default="BlumenHorizon интернет-магазин цветов и подарков в Берлине",
                max_length=500,
                null=True,
                verbose_name="Description в JSON LD для OnlineStore",
            ),
        ),
        migrations.AddField(
            model_name="mainpagemodel",
            name="json_ld_description_en",
            field=models.CharField(
                default="BlumenHorizon интернет-магазин цветов и подарков в Берлине",
                max_length=500,
                null=True,
                verbose_name="Description в JSON LD для OnlineStore",
            ),
        ),
        migrations.AddField(
            model_name="mainpagemodel",
            name="json_ld_description_ru",
            field=models.CharField(
                default="BlumenHorizon интернет-магазин цветов и подарков в Берлине",
                max_length=500,
                null=True,
                verbose_name="Description в JSON LD для OnlineStore",
            ),
        ),
    ]
