# Generated by Django 5.1.3 on 2024-11-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0035_aboutuspagemodel_json_ld_de_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutuspagemodel",
            name="json_ld_de",
        ),
        migrations.RemoveField(
            model_name="aboutuspagemodel",
            name="json_ld_en",
        ),
        migrations.RemoveField(
            model_name="aboutuspagemodel",
            name="json_ld_ru",
        ),
        migrations.RemoveField(
            model_name="contactspagemodel",
            name="json_ld_de",
        ),
        migrations.RemoveField(
            model_name="contactspagemodel",
            name="json_ld_en",
        ),
        migrations.RemoveField(
            model_name="contactspagemodel",
            name="json_ld_ru",
        ),
        migrations.RemoveField(
            model_name="deliverypagemodel",
            name="json_ld_de",
        ),
        migrations.RemoveField(
            model_name="deliverypagemodel",
            name="json_ld_en",
        ),
        migrations.RemoveField(
            model_name="deliverypagemodel",
            name="json_ld_ru",
        ),
        migrations.RemoveField(
            model_name="faqpagemodel",
            name="json_ld_de",
        ),
        migrations.RemoveField(
            model_name="faqpagemodel",
            name="json_ld_en",
        ),
        migrations.RemoveField(
            model_name="faqpagemodel",
            name="json_ld_ru",
        ),
        migrations.RemoveField(
            model_name="mainpagemodel",
            name="json_ld",
        ),
        migrations.RemoveField(
            model_name="mainpagemodel",
            name="json_ld_de",
        ),
        migrations.RemoveField(
            model_name="mainpagemodel",
            name="json_ld_en",
        ),
        migrations.RemoveField(
            model_name="mainpagemodel",
            name="json_ld_ru",
        ),
        migrations.AddField(
            model_name="mainpagemodel",
            name="json_ld_description",
            field=models.CharField(
                default="BlumenHorizon интернет-магазин цветов и подарков в Берлине",
                max_length=500,
                verbose_name="Description в JSON LD для OnlineStore",
            ),
        ),
        migrations.AlterField(
            model_name="aboutuspagemodel",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=4000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="contactspagemodel",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=4000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="deliverypagemodel",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=4000,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="faqpagemodel",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=4000,
                verbose_name="JSON-LD",
            ),
        ),
    ]
