# Generated by Django 5.1.3 on 2024-11-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0036_mainpagemodel_json_ld_description_de_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutuspagemodel",
            name="meta_tags",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                max_length=1000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="aboutuspagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="aboutuspagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="aboutuspagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="contactspagemodel",
            name="meta_tags",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                max_length=1000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="contactspagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="contactspagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="contactspagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="deliverypagemodel",
            name="meta_tags",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                max_length=1000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="deliverypagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="deliverypagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="deliverypagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="faqpagemodel",
            name="meta_tags",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                max_length=1000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="faqpagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="faqpagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="faqpagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagemodel",
            name="json_ld_description",
            field=models.CharField(
                default="Blumen Horizon интернет-магазин цветов и подарков в Берлине",
                max_length=500,
                verbose_name="Description в JSON LD для OnlineStore",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagemodel",
            name="json_ld_description_de",
            field=models.CharField(
                default="Blumen Horizon интернет-магазин цветов и подарков в Берлине",
                max_length=500,
                null=True,
                verbose_name="Description в JSON LD для OnlineStore",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagemodel",
            name="json_ld_description_en",
            field=models.CharField(
                default="Blumen Horizon интернет-магазин цветов и подарков в Берлине",
                max_length=500,
                null=True,
                verbose_name="Description в JSON LD для OnlineStore",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagemodel",
            name="json_ld_description_ru",
            field=models.CharField(
                default="Blumen Horizon интернет-магазин цветов и подарков в Берлине",
                max_length=500,
                null=True,
                verbose_name="Description в JSON LD для OnlineStore",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagemodel",
            name="meta_tags",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                max_length=1000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
    ]
