# Generated by Django 5.1.3 on 2024-11-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0037_alter_aboutuspagemodel_meta_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutuspagemodel",
            name="json_ld_de",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="aboutuspagemodel",
            name="json_ld_en",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="aboutuspagemodel",
            name="json_ld_ru",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="contactspagemodel",
            name="json_ld_de",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="contactspagemodel",
            name="json_ld_en",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="contactspagemodel",
            name="json_ld_ru",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="deliverypagemodel",
            name="json_ld_de",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="deliverypagemodel",
            name="json_ld_en",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AddField(
            model_name="deliverypagemodel",
            name="json_ld_ru",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                max_length=4000,
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
    ]
