# Generated by Django 5.1.3 on 2024-12-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0041_agbpagemodel_impressumpagemodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agbpagemodel",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="agbpagemodel",
            name="json_ld_de",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="agbpagemodel",
            name="json_ld_en",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="agbpagemodel",
            name="json_ld_ru",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="agbpagemodel",
            name="json_ld_uk",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="agbpagemodel",
            name="meta_tags",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>", verbose_name="Мета-теги"
            ),
        ),
        migrations.AlterField(
            model_name="agbpagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="agbpagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="agbpagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="agbpagemodel",
            name="meta_tags_uk",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="impressumpagemodel",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="impressumpagemodel",
            name="json_ld_de",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="impressumpagemodel",
            name="json_ld_en",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="impressumpagemodel",
            name="json_ld_ru",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="impressumpagemodel",
            name="json_ld_uk",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="impressumpagemodel",
            name="meta_tags",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>", verbose_name="Мета-теги"
            ),
        ),
        migrations.AlterField(
            model_name="impressumpagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="impressumpagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="impressumpagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="impressumpagemodel",
            name="meta_tags_uk",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="privacyandpolicypagemodel",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="privacyandpolicypagemodel",
            name="json_ld_de",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="privacyandpolicypagemodel",
            name="json_ld_en",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="privacyandpolicypagemodel",
            name="json_ld_ru",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="privacyandpolicypagemodel",
            name="json_ld_uk",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="privacyandpolicypagemodel",
            name="meta_tags",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>", verbose_name="Мета-теги"
            ),
        ),
        migrations.AlterField(
            model_name="privacyandpolicypagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="privacyandpolicypagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="privacyandpolicypagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="privacyandpolicypagemodel",
            name="meta_tags_uk",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="returnpolicypagemodel",
            name="json_ld",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="returnpolicypagemodel",
            name="json_ld_de",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="returnpolicypagemodel",
            name="json_ld_en",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="returnpolicypagemodel",
            name="json_ld_ru",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="returnpolicypagemodel",
            name="json_ld_uk",
            field=models.TextField(
                default='<script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebPage"\n        }\n</script>',
                null=True,
                verbose_name="JSON-LD",
            ),
        ),
        migrations.AlterField(
            model_name="returnpolicypagemodel",
            name="meta_tags",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>", verbose_name="Мета-теги"
            ),
        ),
        migrations.AlterField(
            model_name="returnpolicypagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="returnpolicypagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="returnpolicypagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="returnpolicypagemodel",
            name="meta_tags_uk",
            field=models.TextField(
                default="<title>Blumen Horizon | </title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
    ]
