# Generated by Django 5.1.3 on 2024-12-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0042_alter_agbpagemodel_json_ld_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mainpagemodel",
            options={
                "verbose_name": "Главная страница",
                "verbose_name_plural": "Главная страница",
            },
        ),
        migrations.AlterModelOptions(
            name="mainpageseoblock",
            options={
                "verbose_name": "Фотография внизу главной страницы",
                "verbose_name_plural": "Фотография внизу главной страницы",
            },
        ),
    ]
