# Generated by Django 5.1.4 on 2024-12-16 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0044_alter_aboutuspagemodel_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agbpagemodel",
            options={
                "verbose_name": "Страница «Условия и положения»",
                "verbose_name_plural": "Страница «Условия и положения»",
            },
        ),
        migrations.AlterModelOptions(
            name="privacyandpolicypagemodel",
            options={
                "verbose_name": "Страница «Условия конфиденциальности и безопасности данных»",
                "verbose_name_plural": "Страница «Условия конфиденциальности и безопасности данных»",
            },
        ),
        migrations.AlterModelOptions(
            name="returnpolicypagemodel",
            options={
                "verbose_name": "Страница «Условия возврата»",
                "verbose_name_plural": "Страница «Условия возврата»",
            },
        ),
    ]
