# Generated by Django 5.1.4 on 2024-12-16 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0045_alter_agbpagemodel_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mainpagemodel",
            options={
                "verbose_name": "1. Главная страница",
                "verbose_name_plural": "1. Главная страница",
            },
        ),
        migrations.AlterModelOptions(
            name="mainpageseoblock",
            options={
                "verbose_name": "3. Фотография внизу главной страницы",
                "verbose_name_plural": "3. Фотография внизу главной страницы",
            },
        ),
        migrations.AlterModelOptions(
            name="mainpagesliderimages",
            options={
                "verbose_name": "2. Фото слайдера вверху главной страницы",
                "verbose_name_plural": "2. Фото слайдера вверху главной страницы",
            },
        ),
    ]
