# Generated by Django 5.1.4 on 2024-12-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0047_remove_aboutuspagemodel_json_ld_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutuspagemodel",
            name="meta_tags",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="aboutuspagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="aboutuspagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="aboutuspagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="aboutuspagemodel",
            name="meta_tags_uk",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="agbpagemodel",
            name="meta_tags",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>", verbose_name="Мета-теги"
            ),
        ),
        migrations.AlterField(
            model_name="agbpagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="agbpagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="agbpagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="agbpagemodel",
            name="meta_tags_uk",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="contactspagemodel",
            name="meta_tags",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="contactspagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="contactspagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="contactspagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="contactspagemodel",
            name="meta_tags_uk",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="deliverypagemodel",
            name="meta_tags",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="deliverypagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="deliverypagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="deliverypagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="deliverypagemodel",
            name="meta_tags_uk",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="faqpagemodel",
            name="meta_tags",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="faqpagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="faqpagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="faqpagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="faqpagemodel",
            name="meta_tags_uk",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="impressumpagemodel",
            name="meta_tags",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>", verbose_name="Мета-теги"
            ),
        ),
        migrations.AlterField(
            model_name="impressumpagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="impressumpagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="impressumpagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="impressumpagemodel",
            name="meta_tags_uk",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagemodel",
            name="meta_tags",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagemodel",
            name="meta_tags_uk",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                max_length=1000,
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="privacyandpolicypagemodel",
            name="meta_tags",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>", verbose_name="Мета-теги"
            ),
        ),
        migrations.AlterField(
            model_name="privacyandpolicypagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="privacyandpolicypagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="privacyandpolicypagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="privacyandpolicypagemodel",
            name="meta_tags_uk",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="returnpolicypagemodel",
            name="meta_tags",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>", verbose_name="Мета-теги"
            ),
        ),
        migrations.AlterField(
            model_name="returnpolicypagemodel",
            name="meta_tags_de",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="returnpolicypagemodel",
            name="meta_tags_en",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="returnpolicypagemodel",
            name="meta_tags_ru",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
        migrations.AlterField(
            model_name="returnpolicypagemodel",
            name="meta_tags_uk",
            field=models.TextField(
                default="<title> | BlumenHorizon</title>",
                null=True,
                verbose_name="Мета-теги",
            ),
        ),
    ]
