# Generated by Django 5.1.3 on 2024-11-21 00:13

from django.db import migrations, models

import catalogue.models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="code",
            field=models.CharField(
                default=catalogue.models.generate_sku,
                max_length=60,
                verbose_name="Код заказа",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_surprise",
            field=models.BooleanField(
                default=False, verbose_name="Доставка с сюрпризом?"
            ),
        ),
    ]
