# Generated by Django 5.1.4 on 2025-03-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="refund_currency_convertasion_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="При возврате",
                max_digits=10,
                null=True,
                verbose_name="Разница конвертации валюты",
            ),
        ),
    ]
