# Generated by Django 5.1.4 on 2025-03-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_order_refund_currency_convertasion_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordercreditadjustment",
            name="payment_system_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Спросить у Виталика",
                max_digits=10,
                null=True,
                verbose_name="Комиссия системы приёма платежей",
            ),
        ),
    ]
