# Generated by Django 5.1.3 on 2024-11-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_order_code_alter_order_is_surprise"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="recipient_name",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="Имя получателя"
            ),
        ),
    ]
