# Generated by Django 5.1.3 on 2024-11-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_order_recipient_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="clarify_address",
            field=models.BooleanField(default=False, verbose_name="Уточнить адрес?"),
        ),
    ]
