# Generated by Django 5.1.3 on 2024-11-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_order_clarify_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "В обработке"),
                    ("declined", "Отказан"),
                    ("awaiting_payment", "Ожидание оплаты"),
                    ("shipping", "В доставке"),
                    ("delivered", "Доставлен"),
                ],
                default="awaiting_payment",
                max_length=20,
                verbose_name="Статус заказа",
            ),
        ),
    ]
