# Generated by Django 5.1.3 on 2024-11-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="building",
            field=models.CharField(max_length=40, null=True, verbose_name="Здание"),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=40, null=True, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(max_length=40, null=True, verbose_name="Страна"),
        ),
        migrations.AlterField(
            model_name="order",
            name="flat",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Квартира/офис"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="postal_code",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Почтовый индекс"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="recipient_name",
            field=models.CharField(
                default="", max_length=80, verbose_name="Имя получателя"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="recipient_phonenumber",
            field=models.CharField(
                default="", max_length=30, verbose_name="Номер телефона получателя"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="street",
            field=models.CharField(max_length=255, null=True, verbose_name="Улица"),
        ),
    ]
