# Generated by Django 5.1.3 on 2024-11-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_alter_order_building_alter_order_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="recipient_address_form",
            field=models.CharField(
                choices=[("Mr.", "Уважаемый"), ("Mrs.", "Уважаемая")],
                default="Mr.",
                max_length=20,
            ),
        ),
    ]
