# Generated by Django 5.1.3 on 2024-11-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_order_recipient_address_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address_form",
            field=models.CharField(
                choices=[("Mr.", "Уважаемый"), ("Mrs.", "Уважаемая")],
                default="Mr.",
                max_length=20,
                verbose_name="Форма обращения к заказчику",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.CharField(
                default="", max_length=80, verbose_name="Имя заказчика"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="recipient_address_form",
            field=models.CharField(
                choices=[("Mr.", "Уважаемый"), ("Mrs.", "Уважаемая")],
                default="Mr.",
                max_length=20,
                verbose_name="Форма обращения к получателю",
            ),
        ),
    ]
