# Generated by Django 5.1.3 on 2024-11-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_order_address_form_order_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="grand_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Сумма заказа",
                max_digits=10,
                verbose_name="Цена",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderbouquets",
            name="quantity",
            field=models.IntegerField(default=0, verbose_name="Количество продукта"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderproducts",
            name="quantity",
            field=models.IntegerField(default=0, verbose_name="Количество продукта"),
            preserve_default=False,
        ),
    ]
