# Generated by Django 5.1.3 on 2024-11-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0009_order_grand_total_orderbouquets_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="grand_total",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Сумма заказа",
                max_digits=10,
                null=True,
                verbose_name="Сумма заказа",
            ),
        ),
    ]
