# Generated by Django 5.1.3 on 2024-11-22 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0010_alter_order_grand_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="sub_total",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Без налога",
                max_digits=10,
                null=True,
                verbose_name="Стоимость без НДС",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tax",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Налоговая стоимость",
                max_digits=10,
                null=True,
                verbose_name="Сумма налога",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_percent",
            field=models.IntegerField(
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="НДС",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="grand_total",
            field=models.DecimalField(
                decimal_places=2,
                help_text="С налогом",
                max_digits=10,
                null=True,
                verbose_name="Итоговая стоимость",
            ),
        ),
    ]
