# Generated by Django 5.1.3 on 2024-11-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0013_order_instructions_order_message_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderbouquets",
            name="product_discount_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Цена продукта cо скидкой",
                max_digits=10,
                verbose_name="Цена",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderbouquets",
            name="product_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Цена продукта",
                max_digits=10,
                verbose_name="Цена",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderbouquets",
            name="product_tax_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Цена продукта с налогом",
                max_digits=10,
                verbose_name="Цена",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderbouquets",
            name="product_tax_price_discounted",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Цена продукта с налогом и скидкой",
                max_digits=10,
                verbose_name="Цена",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderproducts",
            name="product_discount_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Цена продукта cо скидкой",
                max_digits=10,
                verbose_name="Цена",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderproducts",
            name="product_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Цена продукта",
                max_digits=10,
                verbose_name="Цена",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderproducts",
            name="product_tax_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Цена продукта с налогом",
                max_digits=10,
                verbose_name="Цена",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderproducts",
            name="product_tax_price_discounted",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Цена продукта с налогом и скидкой",
                max_digits=10,
                verbose_name="Цена",
            ),
            preserve_default=False,
        ),
    ]
