# Generated by Django 5.1.3 on 2024-11-24 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0014_orderbouquets_product_discount_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderbouquets",
            name="product_discount",
            field=models.IntegerField(
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Скидка на продукт",
            ),
        ),
        migrations.AddField(
            model_name="orderproducts",
            name="product_discount",
            field=models.IntegerField(
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Скидка на продукт",
            ),
        ),
    ]
