# Generated by Django 5.1.3 on 2024-11-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0015_orderbouquets_product_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderbouquets",
            name="product_tax_price_discounted",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Цена продукта со скидкой и налогом",
                max_digits=10,
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="orderproducts",
            name="product_tax_price_discounted",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Цена продукта со скидкой и налогом",
                max_digits=10,
                verbose_name="Цена",
            ),
        ),
    ]
