# Generated by Django 5.1.3 on 2024-11-24 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0016_alter_orderbouquets_product_tax_price_discounted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="grand_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="С налогом",
                max_digits=10,
                verbose_name="Итоговая стоимость",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="sub_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Без налога",
                max_digits=10,
                verbose_name="Чистая стоимость",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="tax",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Стоимость налога",
                max_digits=10,
                verbose_name="Налоговая стоимость",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="tax_percent",
            field=models.IntegerField(
                default=0,
                help_text="%",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="НДС",
            ),
        ),
    ]
