# Generated by Django 5.1.3 on 2024-11-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0017_alter_order_grand_total_alter_order_sub_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderbouquets",
            name="product_discount_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена продукта cо скидкой"
            ),
        ),
        migrations.AlterField(
            model_name="orderbouquets",
            name="product_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена продукта"
            ),
        ),
        migrations.AlterField(
            model_name="orderbouquets",
            name="product_tax_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена продукта с налогом"
            ),
        ),
        migrations.AlterField(
            model_name="orderbouquets",
            name="product_tax_price_discounted",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                verbose_name="Цена продукта со скидкой и налогом",
            ),
        ),
        migrations.AlterField(
            model_name="orderproducts",
            name="product_discount_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена продукта cо скидкой"
            ),
        ),
        migrations.AlterField(
            model_name="orderproducts",
            name="product_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена продукта"
            ),
        ),
        migrations.AlterField(
            model_name="orderproducts",
            name="product_tax_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена продукта с налогом"
            ),
        ),
        migrations.AlterField(
            model_name="orderproducts",
            name="product_tax_price_discounted",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                verbose_name="Цена продукта со скидкой и налогом",
            ),
        ),
    ]
