# Generated by Django 5.1.3 on 2024-11-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0018_alter_orderbouquets_product_discount_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="building",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Здание"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(default="", max_length=40, verbose_name="Город"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(default="", max_length=40, verbose_name="Страна"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="flat",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Квартира/офис"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="instructions",
            field=models.TextField(
                blank=True,
                max_length=800,
                null=True,
                verbose_name="Инструкции к доставке",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="message_card",
            field=models.TextField(
                blank=True, max_length=10000, null=True, verbose_name="Записка к букету"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Почтовый индекс"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="street",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Улица"
            ),
        ),
    ]
