# Generated by Django 5.1.3 on 2024-11-25 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0019_alter_order_building_alter_order_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 11, 25, 14, 13, 6, 759415, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата доставки",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_time",
            field=models.TimeField(
                default=datetime.datetime(
                    2024, 11, 25, 14, 13, 17, 372509, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Время доставки",
            ),
            preserve_default=False,
        ),
    ]
