# Generated by Django 5.1.4 on 2024-12-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0020_order_delivery_date_order_delivery_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="session_key",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
