# Generated by Django 5.1.3 on 2024-12-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0021_order_session_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="language_code",
            field=models.CharField(
                default="de", max_length=2, verbose_name="Язык пользователя на сайте"
            ),
            preserve_default=False,
        ),
    ]
