# Generated by Django 5.1.4 on 2024-12-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0022_order_language_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderbouquets",
            options={
                "verbose_name": "Букет в заказе",
                "verbose_name_plural": "Букеты в заказе",
            },
        ),
        migrations.AlterModelOptions(
            name="orderproducts",
            options={
                "verbose_name": "Продукт в заказе",
                "verbose_name_plural": "Продукты в заказе",
            },
        ),
    ]
