# Generated by Django 5.1.4 on 2025-01-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0023_alter_orderbouquets_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_agreement_accepted",
            field=models.BooleanField(
                default=False, verbose_name="Соглашение с AGB и Datenschutz"
            ),
        ),
    ]
