# Generated by Django 5.1.4 on 2025-02-07 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0026_rename_product_price_orderbouquets_base_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "brutto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="С налогом",
                        max_digits=10,
                        null=True,
                        verbose_name="Себестоимость",
                    ),
                ),
                (
                    "netto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Без налога",
                        max_digits=10,
                        null=True,
                        verbose_name="Себестоимость",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Налог",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Номер чека"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="bills/%Y-%m-%d",
                        verbose_name="Фото чека",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Florist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("contact", models.TextField(verbose_name="Контакт флориста")),
                (
                    "address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Адрес флориста"
                    ),
                ),
                (
                    "vat_id",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="НДС/Налоговый номер флориста",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание флориста"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="order",
            name="bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="cart.bill",
                verbose_name="Чек",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="florist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bills",
                to="cart.florist",
                verbose_name="Флорист выдавший чек",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="florist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="cart.florist",
                verbose_name="Флорист-исполнитель",
            ),
        ),
    ]
