# Generated by Django 5.1.4 on 2025-02-02 16:24

from django.db import migrations, models


def set_product_taxes(apps, schema_editor):
    OrderProducts = apps.get_model("cart", "OrderProducts")

    for order_product in OrderProducts.objects.all():
        if order_product.product:
            order_product.taxes = order_product.product.taxes
            order_product.save()


def set_bouquet_taxes(apps, schema_editor):
    OrderBouquets = apps.get_model("cart", "OrderBouquets")

    for order_bouquet in OrderBouquets.objects.all():
        if order_bouquet.product:
            order_bouquet.taxes = order_bouquet.product.taxes
            order_bouquet.save()


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0026_rename_product_discount_orderbouquets_discount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderbouquets",
            name="taxes",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Всего заплаченных налогов",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_bouquet_taxes),
        migrations.AddField(
            model_name="orderproducts",
            name="taxes",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Всего заплаченных налогов",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_product_taxes),
    ]
