# Generated by Django 5.1.4 on 2025-02-02 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0027_orderbouquets_taxes_orderproducts_taxes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderbouquets",
            old_name="price",
            new_name="base_price",
        ),
        migrations.RenameField(
            model_name="orderproducts",
            old_name="price",
            new_name="base_price",
        ),
    ]
