# Generated by Django 5.1.4 on 2025-02-07 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0027_bill_florist_order_bill_bill_florist_order_florist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bill",
            options={"verbose_name": "ЧЕК", "verbose_name_plural": "ЧЕКИ"},
        ),
        migrations.AlterModelOptions(
            name="florist",
            options={"verbose_name": "ФЛОРИСТ", "verbose_name_plural": "ФЛОРИСТЫ"},
        ),
    ]
