# Generated by Django 5.1.4 on 2025-02-07 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0028_alter_bill_options_alter_florist_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="florist",
        ),
        migrations.AlterField(
            model_name="bill",
            name="florist",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bills",
                to="cart.florist",
                verbose_name="Флорист выдавший чек",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="bill",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="cart.bill",
                verbose_name="Чек",
            ),
        ),
    ]
