# Generated by Django 5.1.4 on 2025-02-07 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0029_remove_order_florist_alter_bill_florist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="florist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bills",
                to="cart.florist",
                verbose_name="Флорист выдавший чек",
            ),
        ),
    ]
