# Generated by Django 5.1.4 on 2025-02-07 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0030_alter_bill_florist"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bills",
                to="cart.order",
                verbose_name="Заказ",
            ),
        ),
    ]
