# Generated by Django 5.1.4 on 2025-02-07 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0031_bill_order"),
        ("catalogue", "0063_alter_bouquet_tax_percent_alter_product_tax_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderbouquets",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bouquets",
                to="cart.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AlterField(
            model_name="orderbouquets",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="catalogue.bouquet",
                verbose_name="Букет",
            ),
        ),
    ]
