# Generated by Django 5.1.4 on 2025-02-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0036_alter_orderbouquets_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="tax_percent",
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_taxes",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Спросить у Виталика",
                max_digits=10,
                null=True,
                verbose_name="Налог Stripe за транзакцию",
            ),
        ),
    ]
