# Generated by Django 5.1.4 on 2025-02-07 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0027_auto_20250204_2156"),
        ("cart", "0036_alter_orderbouquets_order_and_more"),
    ]

    operations = []
