# Generated by Django 5.1.4 on 2025-02-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0037_remove_order_tax_percent_order_stripe_taxes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="bills/%Y-%m-%d",
                verbose_name="Фото чека",
            ),
        ),
    ]
