# Generated by Django 5.1.4 on 2025-02-07 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0037_alter_orderbouquets_order_alter_orderproducts_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderbouquets",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bouquets",
                to="cart.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AlterField(
            model_name="orderproducts",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="cart.order",
                verbose_name="Заказ",
            ),
        ),
    ]
