# Generated by Django 5.1.4 on 2025-02-08 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0039_alter_bill_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="order",
        ),
    ]
