# Generated by Django 5.1.4 on 2025-02-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0037_merge_20250208_0039"),
        ("cart", "0040_remove_bill_order"),
    ]

    operations = []
