# Generated by Django 5.1.4 on 2025-02-11 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0040_remove_bill_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "owner_name",
                    models.CharField(max_length=255, verbose_name="Имя владельца"),
                ),
                (
                    "number",
                    models.CharField(max_length=255, verbose_name="Номер счёта"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="bill",
            name="is_paid",
            field=models.BooleanField(default=True, verbose_name="Оплачено?"),
        ),
        migrations.AddField(
            model_name="bill",
            name="refund_reciept",
            field=models.FileField(
                blank=True,
                help_text="В случае если флорист сделал свою работу плохо и мы добились возврата (фото/PDF-файл)",
                null=True,
                upload_to="bills/%Y-%m-%d",
                verbose_name="Подтверждение возврата от флориста",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="account_paid_funds",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bills",
                to="cart.bankaccount",
                verbose_name="Банковский счёт с которого провели оплату",
            ),
        ),
        migrations.CreateModel(
            name="RefundReciept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        help_text="В случае если флорист сделал свою работу плохо и мы добились возврата (фото/PDF-файл)",
                        null=True,
                        upload_to="bills/%Y-%m-%d",
                        verbose_name="Подтверждение возврата от флориста",
                    ),
                ),
                ("issue_date", models.DateTimeField(verbose_name="Дата выдачи")),
                ("reciept_date", models.DateTimeField(verbose_name="Дата поступления")),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="В случае если сошлись на частичном возврате - указать эту сумму.",
                        max_digits=10,
                        null=True,
                        verbose_name="Сумма возврата",
                    ),
                ),
                (
                    "account_received_funds",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_receipts",
                        to="cart.bankaccount",
                        verbose_name="Банковский счёт на который вернули деньги",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
