# Generated by Django 5.1.4 on 2025-02-11 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0041_bankaccount_bill_is_paid_bill_refund_reciept_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RefundReciept",
            new_name="RefundReceipt",
        ),
        migrations.RenameField(
            model_name="bill",
            old_name="refund_reciept",
            new_name="refund_receipt",
        ),
        migrations.RenameField(
            model_name="refundreceipt",
            old_name="reciept_date",
            new_name="receipt_date",
        ),
    ]
