# Generated by Django 5.1.4 on 2025-02-11 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0042_rename_refundreciept_refundreceipt_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bankaccount",
            options={
                "verbose_name": "“Банковский счёт”",
                "verbose_name_plural": "“Банковские счета”",
            },
        ),
        migrations.AlterModelOptions(
            name="refundreceipt",
            options={
                "verbose_name": "“Чек возврата”",
                "verbose_name_plural": "“Чеки возврата”",
            },
        ),
        migrations.AlterField(
            model_name="bill",
            name="refund_receipt",
            field=models.ForeignKey(
                blank=True,
                help_text="В случае если флорист сделал свою работу плохо и мы добились возврата",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bills",
                to="cart.refundreceipt",
            ),
        ),
        migrations.AlterField(
            model_name="refundreceipt",
            name="refund_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Указано в чеке возврата",
                max_digits=10,
                null=True,
                verbose_name="Сумма возврата",
            ),
        ),
    ]
