# Generated by Django 5.1.4 on 2025-02-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0043_alter_bankaccount_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="number",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Номер счёта"
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="owner_name",
            field=models.CharField(max_length=255, verbose_name="Имя владельца счёта"),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название банка"),
        ),
    ]
