# Generated by Django 5.1.4 on 2025-02-11 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0044_alter_bankaccount_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="refund_receipt",
            field=models.ForeignKey(
                blank=True,
                help_text="В случае если флорист сделал свою работу плохо и мы добились возврата",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bills",
                to="cart.refundreceipt",
                verbose_name="Чек возврата от флориста",
            ),
        ),
    ]
