# Generated by Django 5.1.4 on 2025-02-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0045_alter_bill_refund_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
        migrations.AddField(
            model_name="bill",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
        migrations.AddField(
            model_name="order",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
        migrations.AddField(
            model_name="refundreceipt",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
    ]
