# Generated by Django 5.1.4 on 2025-02-12 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0046_bankaccount_comment_bill_comment_order_comment_and_more"),
        ("catalogue", "0064_alter_bouquet_tax_percent_alter_product_tax_percent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="refundreceipt",
            name="image",
            field=models.FileField(
                blank=True,
                help_text="В случае если флорист сделал свою работу плохо и мы добились возврата (фото/PDF-файл)",
                null=True,
                upload_to="refund_receipts/%Y-%m-%d",
                verbose_name="Подтверждение возврата от флориста",
            ),
        ),
        migrations.CreateModel(
            name="OrderCreditAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[("credit", "Кредит"), ("debit", "Дебит")],
                        help_text="Выберите тип корректировки: Кредит - пополнение от клиента, Дебит - возврат клиенту",
                        max_length=10,
                        verbose_name="Тип корректировки",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Сумма корректировки",
                        max_digits=10,
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Опишите причину корректировки или дополнительные детали",
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True,
                        help_text="Ссылка на внешний источник или номер транзакции",
                        max_length=255,
                        null=True,
                        verbose_name="Внешняя ссылка",
                    ),
                ),
                (
                    "is_reported_to_tax",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте, если транзакция была отправлена в налоговую",
                        verbose_name="Сообщено в налоговую",
                    ),
                ),
                (
                    "reporting_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата, когда транзакция была отправлена в налоговую",
                        null=True,
                        verbose_name="Дата отправки в налоговую",
                    ),
                ),
                (
                    "issue_date",
                    models.DateTimeField(
                        help_text="Дата, когда была инициирована корректировка",
                        verbose_name="Дата инициации",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        help_text="Загрузите фото или PDF-файл, подтверждающий транзакцию",
                        null=True,
                        upload_to="order_adjustments/credit/%Y-%m-%d",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "receipt_date",
                    models.DateTimeField(
                        help_text="Дата, когда средства были зачислены на счет",
                        verbose_name="Дата поступления средств",
                    ),
                ),
                (
                    "taxes",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Сумма налога, уплаченная клиентом в рамках этой корректировки",
                        max_digits=10,
                        verbose_name="Всего заплаченных налогов клиентом",
                    ),
                ),
                (
                    "account_received_funds",
                    models.ForeignKey(
                        help_text="Выберите банковский счёт, на который были зачислены средства",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders_credit_adjustments",
                        to="cart.bankaccount",
                        verbose_name="Банковский счёт на который поступили деньги",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Заказ, к которому относится корректировка",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_adjustments",
                        to="cart.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Сотрудник, который обработал данную транзакцию",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обработано сотрудником",
                    ),
                ),
                (
                    "tax_percent",
                    models.ForeignKey(
                        default=1,
                        help_text="Выберите налоговую ставку, применимую к данной операции. Вычисляется после скидки.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders_credit_adjustments",
                        to="catalogue.taxpercent",
                        verbose_name="Налоговая ставка",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderDebitAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[("credit", "Кредит"), ("debit", "Дебит")],
                        help_text="Выберите тип корректировки: Кредит - пополнение от клиента, Дебит - возврат клиенту",
                        max_length=10,
                        verbose_name="Тип корректировки",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Сумма корректировки",
                        max_digits=10,
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Опишите причину корректировки или дополнительные детали",
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True,
                        help_text="Ссылка на внешний источник или номер транзакции",
                        max_length=255,
                        null=True,
                        verbose_name="Внешняя ссылка",
                    ),
                ),
                (
                    "is_reported_to_tax",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте, если транзакция была отправлена в налоговую",
                        verbose_name="Сообщено в налоговую",
                    ),
                ),
                (
                    "reporting_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата, когда транзакция была отправлена в налоговую",
                        null=True,
                        verbose_name="Дата отправки в налоговую",
                    ),
                ),
                (
                    "issue_date",
                    models.DateTimeField(
                        help_text="Дата, когда была инициирована корректировка",
                        verbose_name="Дата инициации",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        help_text="Загрузите фото или PDF-файл, подтверждающий транзакцию",
                        null=True,
                        upload_to="order_adjustments/debit/%Y-%m-%d",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "transfer_date",
                    models.DateTimeField(
                        help_text="Дата, когда средства были отправлены клиенту",
                        verbose_name="Дата отправки средств",
                    ),
                ),
                (
                    "account_received_funds",
                    models.ForeignKey(
                        help_text="Выберите банковский счёт, с которого были возвращены средства",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders_debit_adjustments",
                        to="cart.bankaccount",
                        verbose_name="Банковский счёт с которого вернули деньги",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Заказ, к которому относится корректировка",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="debit_adjustments",
                        to="cart.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Сотрудник, который обработал данную транзакцию",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обработано сотрудником",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
