# Generated by Django 5.1.4 on 2025-02-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0048_alter_bankaccount_options_alter_bill_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_reported_to_tax",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте, если транзакция заказ был отправлен в налоговую",
                verbose_name="Сообщено в налоговую",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="reporting_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата, когда заказ был отправлен в налоговую",
                null=True,
                verbose_name="Дата отправки в налоговую",
            ),
        ),
    ]
