# Generated by Django 5.1.4 on 2025-02-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0049_order_is_reported_to_tax_order_reporting_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="is_reported_to_tax",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте, если заказ был отправлен в налоговую",
                verbose_name="Сообщено в налоговую",
            ),
        ),
    ]
