# Generated by Django 5.1.4 on 2025-02-12 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0041_merge_0037_merge_20250208_0039_0040_remove_bill_order"),
        ("cart", "0050_alter_order_is_reported_to_tax"),
    ]

    operations = []
