# Generated by Django 5.1.4 on 2025-03-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0050_alter_order_is_reported_to_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderbouquets",
            name="supplier_paid_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Заплаченная себестоимость поставщику",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderbouquets",
            name="supplier_paid_taxes",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Всего заплаченных налогов за продукт у поставщика",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderbouquets",
            name="supplier_vat_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Ставка НДС от поставщика",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderproducts",
            name="supplier_paid_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Заплаченная себестоимость поставщику",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderproducts",
            name="supplier_paid_taxes",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Всего заплаченных налогов за продукт у поставщика",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderproducts",
            name="supplier_vat_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Ставка НДС от поставщика",
            ),
            preserve_default=False,
        ),
    ]
