# Generated by Django 5.1.4 on 2025-03-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0051_orderbouquets_supplier_paid_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="stripe_taxes",
            new_name="payment_system_comissions"
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_system_comissions",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Спросить у Виталика",
                max_digits=10,
                null=True,
                verbose_name="Комиссия системы приёма платежей",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "В обработке"),
                    ("declined", "Возврат"),
                    ("awaiting_payment", "Ожидание оплаты"),
                    ("shipping", "В доставке"),
                    ("delivered", "Доставлен"),
                ],
                default="awaiting_payment",
                max_length=20,
                verbose_name="Статус заказа",
            ),
        ),
        migrations.AlterField(
            model_name="orderbouquets",
            name="supplier_paid_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Заплаченная себестоимость поставщику",
            ),
        ),
        migrations.AlterField(
            model_name="orderbouquets",
            name="supplier_paid_taxes",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Всего заплаченных налогов за продукт у поставщика",
            ),
        ),
        migrations.AlterField(
            model_name="orderbouquets",
            name="supplier_vat_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Ставка НДС от поставщика",
            ),
        ),
        migrations.AlterField(
            model_name="orderproducts",
            name="supplier_paid_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Заплаченная себестоимость поставщику",
            ),
        ),
        migrations.AlterField(
            model_name="orderproducts",
            name="supplier_paid_taxes",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Всего заплаченных налогов за продукт у поставщика",
            ),
        ),
        migrations.AlterField(
            model_name="orderproducts",
            name="supplier_vat_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Ставка НДС от поставщика",
            ),
        ),
    ]
