# Generated by Django 5.1.4 on 2025-03-06 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0052_remove_order_stripe_taxes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="payment_system_comissions",
            new_name="payment_system_fee",
        ),
    ]
