# Generated by Django 5.1.4 on 2025-03-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0053_rename_payment_system_comissions_order_payment_system_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(
                max_length=254, verbose_name="Способ связи с заказчиком"
            ),
        ),
    ]
