# Generated by Django 5.1.4 on 2025-03-12 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0051_merge_20250212_0125'),
        ('cart', '0054_alter_order_email'),
    ]

    operations = [
    ]
