# Generated by Django 5.1.4 on 2025-03-12 13:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0054_alter_order_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="earned_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Менеджер принёсший заказ",
            ),
        ),
        migrations.AlterField(
            model_name="orderbouquets",
            name="supplier_vat_rate",
            field=models.IntegerField(
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Ставка НДС от поставщика",
            ),
        ),
        migrations.AlterField(
            model_name="orderproducts",
            name="supplier_vat_rate",
            field=models.IntegerField(
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Ставка НДС от поставщика",
            ),
        ),
    ]
