# Generated by Django 5.1.4 on 2025-03-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0055_alter_order_user_and_more'),
        ('cart', '0055_merge_0051_merge_20250212_0125_0054_alter_order_email'),
    ]

    operations = [
    ]
