# Generated by Django 5.1.4 on 2025-03-12 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0055_merge_0051_merge_20250212_0125_0054_alter_order_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="earned_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Менеджер принёсший заказ",
            ),
        ),
    ]
