# Generated by Django 5.1.4 on 2025-03-12 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0056_order_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderbouquets",
            name="supplier_vat_rate",
            field=models.IntegerField(
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Ставка НДС от поставщика",
            ),
        ),
        migrations.AlterField(
            model_name="orderproducts",
            name="supplier_vat_rate",
            field=models.IntegerField(
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Ставка НДС от поставщика",
            ),
        ),
    ]
