# Generated by Django 5.1.4 on 2025-03-12 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0056_merge_20250312_1421'),
        ('cart', '0056_merge_20250312_1429'),
    ]

    operations = [
    ]
