# Generated by Django 5.1.4 on 2025-03-12 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0056_order_manager_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="С налогом",
                max_digits=10,
                null=True,
                verbose_name="Стоимость доставки",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_vat_rate",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Процент НДС на доставку",
            ),
        ),
    ]
