# Generated by Django 5.1.2 on 2024-10-21 15:54

import django.db.models.deletion
import products.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(unique=True, verbose_name="Название в ссылке"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный?"),
                ),
                (
                    "image",
                    models.ImageField(
                        default="defaults/no-image.webp",
                        upload_to="categories/%Y-%m-%d",
                        verbose_name="Картинка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
                (
                    "hex_code",
                    models.CharField(
                        help_text="Введите HEX-код цвета, например: #FFFFFF (белый) или #FFF (сокращённый формат).",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "verbose_name": "Цвет",
                "verbose_name_plural": "Цвета",
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Трехзначный код валюты, например: USD, EUR",
                        max_length=3,
                        unique=True,
                        verbose_name="Код валюты",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Символ валюты, например: $, €",
                        max_length=5,
                        verbose_name="Знак валюты",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=1.0,
                        help_text="Курс относительно базовой валюты.",
                        max_digits=10,
                        verbose_name="Курс обмена",
                    ),
                ),
            ],
            options={
                "verbose_name": "Валюта",
                "verbose_name_plural": "Валюты",
            },
        ),
        migrations.CreateModel(
            name="Flower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "Цветок",
                "verbose_name_plural": "Цветы",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(unique=True, verbose_name="Название в ссылке"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный?"),
                ),
                (
                    "image",
                    models.ImageField(
                        default="defaults/no-image.webp",
                        upload_to="products/%Y-%m-%d",
                        verbose_name="Картинка",
                    ),
                ),
                ("description", tinymce.models.HTMLField(verbose_name="Описание")),
                ("specs", tinymce.models.HTMLField(verbose_name="Характеристики")),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="До десяти значений, из которых два занимает плавающая запятая",
                        max_digits=10,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        help_text="Выберите валюту для цены.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.currency",
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="products.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цена продукта",
                "verbose_name_plural": "Цены продуктов",
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(unique=True, verbose_name="Название в ссылке"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный?"),
                ),
                (
                    "image",
                    models.ImageField(
                        default="defaults/no-image.webp",
                        upload_to="subcategories/%Y-%m-%d",
                        verbose_name="Картинка",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="products.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подкатегория",
                "verbose_name_plural": "Подкатегории",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="products.subcategory",
                verbose_name="Подкатегория",
            ),
        ),
        migrations.CreateModel(
            name="Bouquet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(unique=True, verbose_name="Название в ссылке"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный?"),
                ),
                (
                    "image",
                    models.ImageField(
                        default="defaults/no-image.webp",
                        upload_to="products/%Y-%m-%d",
                        verbose_name="Картинка",
                    ),
                ),
                ("description", tinymce.models.HTMLField(verbose_name="Описание")),
                ("specs", tinymce.models.HTMLField(verbose_name="Характеристики")),
                ("size", models.IntegerField(verbose_name="Диаметр букета")),
                (
                    "amount_of_flowers",
                    models.IntegerField(verbose_name="Количество цветов в букете"),
                ),
                (
                    "colors",
                    models.ManyToManyField(
                        help_text="Выберите какого цвета букет.",
                        related_name="bouquets",
                        to="products.color",
                        verbose_name="Цвета",
                    ),
                ),
                (
                    "flowers",
                    models.ManyToManyField(
                        help_text="Выберите какие цветы в букете.",
                        related_name="bouquets",
                        to="products.flower",
                        verbose_name="Цветы",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="products.subcategory",
                        verbose_name="Подкатегория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Букет",
                "verbose_name_plural": "Букеты",
            },
        ),
    ]
