# Generated by Django 5.1.2 on 2024-10-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productprice",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="productprice",
            name="product",
        ),
        migrations.DeleteModel(
            name="Currency",
        ),
        migrations.DeleteModel(
            name="ProductPrice",
        ),
    ]
