# Generated by Django 5.1.2 on 2024-10-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_productprice_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bouquet",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=1000,
                help_text="Цена продукта до 10ти значений, два из которых плавающая запятая. Т.е. до 99999999.99",
                max_digits=10,
                verbose_name="Цена",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=1000,
                help_text="Цена продукта до 10ти значений, два из которых плавающая запятая. Т.е. до 99999999.99",
                max_digits=10,
                verbose_name="Цена",
            ),
            preserve_default=False,
        ),
    ]
