# Generated by Django 5.1.2 on 2024-10-21 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_bouquet_image_remove_product_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bouquetimage",
            old_name="product",
            new_name="bouquet",
        ),
    ]
