# Generated by Django 5.1.2 on 2024-10-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_rename_product_bouquetimage_bouquet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                default="defaults/no-image.webp",
                upload_to="products/%Y-%m-%d/",
                verbose_name="Изображение",
            ),
        ),
    ]
