# Generated by Django 5.1.2 on 2024-10-22 09:59

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="hex_code",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                help_text="Введите HEX-код цвета, например: #FFFFFF (белый) или #FFF (сокращённый формат).",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="HEX код цвета (#f4678a к примеру)",
            ),
        ),
        migrations.AlterField(
            model_name="color",
            name="name",
            field=models.CharField(max_length=15, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="flower",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Название"),
        ),
    ]
