# Generated by Django 5.1.2 on 2024-10-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_color_hex_code_alter_color_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(
                max_length=20, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(
                max_length=20, null=True, unique=True, verbose_name="Название"
            ),
        ),
    ]
