# Generated by Django 5.1.2 on 2024-10-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_category_name_en_category_name_ru"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug_en",
            field=models.SlugField(
                null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="slug_ru",
            field=models.SlugField(
                null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
    ]
