# Generated by Django 5.1.2 on 2024-10-22 11:50

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_category_slug_en_category_slug_ru"),
    ]

    operations = [
        migrations.AddField(
            model_name="bouquet",
            name="description_en",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="bouquet",
            name="description_ru",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="bouquet",
            name="name_en",
            field=models.CharField(
                max_length=20, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="bouquet",
            name="name_ru",
            field=models.CharField(
                max_length=20, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="bouquet",
            name="slug_en",
            field=models.SlugField(
                null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AddField(
            model_name="bouquet",
            name="slug_ru",
            field=models.SlugField(
                null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AddField(
            model_name="bouquet",
            name="specs_en",
            field=tinymce.models.HTMLField(null=True, verbose_name="Характеристики"),
        ),
        migrations.AddField(
            model_name="bouquet",
            name="specs_ru",
            field=tinymce.models.HTMLField(null=True, verbose_name="Характеристики"),
        ),
        migrations.AddField(
            model_name="color",
            name="name_en",
            field=models.CharField(max_length=15, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="color",
            name="name_ru",
            field=models.CharField(max_length=15, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="flower",
            name="name_en",
            field=models.CharField(max_length=30, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="flower",
            name="name_ru",
            field=models.CharField(max_length=30, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ru",
            field=tinymce.models.HTMLField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(
                max_length=20, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ru",
            field=models.CharField(
                max_length=20, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="slug_en",
            field=models.SlugField(
                null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="slug_ru",
            field=models.SlugField(
                null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="specs_en",
            field=tinymce.models.HTMLField(null=True, verbose_name="Характеристики"),
        ),
        migrations.AddField(
            model_name="product",
            name="specs_ru",
            field=tinymce.models.HTMLField(null=True, verbose_name="Характеристики"),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="name_en",
            field=models.CharField(
                max_length=20, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="name_ru",
            field=models.CharField(
                max_length=20, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="slug_en",
            field=models.SlugField(
                null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="slug_ru",
            field=models.SlugField(
                null=True, unique=True, verbose_name="Название в ссылке"
            ),
        ),
    ]
