# Generated by Django 5.1.2 on 2024-10-22 13:15

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_alter_subcategory_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="bouquet",
            name="discount",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Скидка",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Скидка",
            ),
        ),
        migrations.AlterField(
            model_name="color",
            name="hex_code",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                help_text="Введите HEX-код цвета, например: #FFFFFF (белый) или #FFF (сокращённый формат).",
                image_field=None,
                max_length=25,
                samples=None,
                unique=True,
                verbose_name="HEX код цвета (#f4678a к примеру)",
            ),
        ),
        migrations.AlterField(
            model_name="color",
            name="name",
            field=models.CharField(max_length=15, unique=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="color",
            name="name_en",
            field=models.CharField(
                max_length=15, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="color",
            name="name_ru",
            field=models.CharField(
                max_length=15, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="flower",
            name="name",
            field=models.CharField(max_length=30, unique=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="flower",
            name="name_en",
            field=models.CharField(
                max_length=30, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="flower",
            name="name_ru",
            field=models.CharField(
                max_length=30, null=True, unique=True, verbose_name="Название"
            ),
        ),
    ]
