# Generated by Django 5.1.2 on 2024-10-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0013_alter_bouquet_subcategory_alter_product_subcategory_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="products/%Y-%m-%d/", verbose_name="Изображение"
            ),
        ),
    ]
