# Generated by Django 5.1.2 on 2024-10-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="products_media/%Y-%m-%d/", verbose_name="Изображение"
            ),
        ),
    ]
