# Generated by Django 5.1.2 on 2024-10-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bouquet",
            name="name",
            field=models.CharField(max_length=40, unique=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="bouquet",
            name="name_en",
            field=models.CharField(
                max_length=40, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="bouquet",
            name="name_ru",
            field=models.CharField(
                max_length=40, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=40, unique=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_en",
            field=models.CharField(
                max_length=40, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_ru",
            field=models.CharField(
                max_length=40, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=40, unique=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_en",
            field=models.CharField(
                max_length=40, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_ru",
            field=models.CharField(
                max_length=40, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(max_length=40, unique=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="name_en",
            field=models.CharField(
                max_length=40, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="name_ru",
            field=models.CharField(
                max_length=40, null=True, unique=True, verbose_name="Название"
            ),
        ),
    ]
